-- Canonical job_id is TEXT. Do not ALTER it to uuid.
ALTER TABLE public.business_events ADD COLUMN IF NOT EXISTS event_type text;
ALTER TABLE public.business_events ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE public.business_events ADD COLUMN IF NOT EXISTS entity_type text;
ALTER TABLE public.business_events ADD COLUMN IF NOT EXISTS entity_id text;
ALTER TABLE public.business_events ADD COLUMN IF NOT EXISTS correlation_id uuid;
ALTER TABLE public.business_events ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE public.business_events ADD COLUMN IF NOT EXISTS attribution_status text;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS org_id uuid;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS scope_json jsonb;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS pricing_json jsonb;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS accepted_at timestamptz;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS site_address text;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS scheduled_at timestamptz;
UPDATE public.jobs SET org_id='00000000-0000-0000-0000-000000000001' WHERE org_id IS NULL;
CREATE TABLE IF NOT EXISTS public.purchase_orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_id uuid);
CREATE TABLE IF NOT EXISTS public.job_documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_id uuid);
CREATE TABLE IF NOT EXISTS public.po_communications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_id uuid);
CREATE TABLE IF NOT EXISTS public.job_media (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_id uuid);
CREATE TABLE IF NOT EXISTS public.job_assignments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), job_id uuid);
