// deno-fmt-ignore-file -- one invoice per line keeps the 112-row acceptance table reviewable.
// Acceptance fixture: the Xero open receivables book of 29 Sep 2026, 15:19 Perth
// (07:19 UTC), with each invoice's backend job status and Clear Debt copy class.
//
// Source: Firstmate data `debt-baseline-s2/report.md`, appendix "every open invoice
// (112), as classified", read live from Xero through the read-only SecureSuite tools.
// Rebuilt row for row from that appendix. Nothing here is invented:
//   - Client contact names are pseudonymised ("Client NN", one per real contact), and
//     the one reference carrying a client's name is redacted. The rules never read a
//     client's name; builder contact names are kept exactly because the payer table
//     keys on them.
//   - The appendix carries no Xero InvoiceIDs, so each row gets a fixture-only UUID
//     derived from its invoice number. It is a key, not a Xero identity.
//   - The appendix carries no line text. Two rows carry the one line the baseline
//     report quotes for them (see line_source). Every other row has no line text, so
//     builder work types other than those named in a reference fall back to make-safe.
//     No acceptance figure depends on line text.
//   - job_first_payment is null (not measured on 29 Sep). The only progress claim,
//     INV-1477, is decided by the captain's correction, not by a first payment.
//   - copy_status / copy_class are the backend copy (xero_invoices) as read the same
//     afternoon: six rows the copy wrongly marks DELETED, every other row AUTHORISED at
//     the same amount and due date (debt-baseline-s2 section 2).
//   - baseline_* fields are the report's own reading, kept for comparison only.

export interface DebtBookFixtureRow {
  invoice_number: string
  contact_name: string
  reference: string
  due_date: string
  amount_due: number
  line_descriptions: string[]
  line_source: string | null
  job_number: string | null
  job_status: string | null
  job_first_payment: boolean | null
  copy_status: 'AUTHORISED' | 'DELETED'
  copy_class: string | null
  baseline_class: string
  baseline_days_over: number
  baseline_counts_as_debt: boolean
}

/** Perth calendar date and UTC instant the book was read. */
export const DEBT_BOOK_FIXTURE_READ_AT = '2026-09-29T07:19:40.000Z'
export const DEBT_BOOK_FIXTURE_PERTH_DATE = '2026-09-29'

/** Fixture-only stand-in for a Xero InvoiceID (the baseline appendix has none). */
export function debtBookFixtureInvoiceId(invoiceNumber: string): string {
  const digits = invoiceNumber.replace(/\D/g, '').padStart(12, '0')
  return `00000000-0000-4000-8000-${digits}`
}

export const DEBT_BOOK_FIXTURE_2026_09_29: DebtBookFixtureRow[] = [
  { invoice_number: "INV-0290", contact_name: "Client 01", reference: "F-FD-R", due_date: "2026-03-14", amount_due: 704, line_descriptions: ["Remaining quote amount"], line_source: "debt-baseline-s2 section 3.4 D quotes this line for INV-0290", job_number: null, job_status: "invoiced", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "final", baseline_days_over: 199, baseline_counts_as_debt: true },
  { invoice_number: "INV-0524", contact_name: "Client 02", reference: "PRIVATE [client name redacted]", due_date: "2026-06-09", amount_due: 885.5, line_descriptions: [], line_source: null, job_number: null, job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "final", baseline_days_over: 112, baseline_counts_as_debt: true },
  { invoice_number: "INV-0937", contact_name: "Client 03", reference: "SWF-26556-FINBAL", due_date: "2026-07-10", amount_due: 1256.75, line_descriptions: [], line_source: null, job_number: "SWF-26556", job_status: "final_payment", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "final", baseline_days_over: 81, baseline_counts_as_debt: true },
  { invoice_number: "INV-1069", contact_name: "Client 04", reference: "SWF-26677-FINBAL", due_date: "2026-07-29", amount_due: 2003.93, line_descriptions: [], line_source: null, job_number: "SWF-26677", job_status: "final_payment", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "final", baseline_days_over: 62, baseline_counts_as_debt: true },
  { invoice_number: "INV-1190", contact_name: "Client 05", reference: "SWF-261053-FINBAL", due_date: "2026-08-11", amount_due: 26.75, line_descriptions: [], line_source: null, job_number: "SWF-261053", job_status: "invoiced", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "final", baseline_days_over: 49, baseline_counts_as_debt: true },
  { invoice_number: "INV-1236", contact_name: "Client 06", reference: "SWF-26091-A-FINBAL", due_date: "2026-08-18", amount_due: 1025.06, line_descriptions: [], line_source: null, job_number: "SWF-26091", job_status: "rectification", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "final", baseline_days_over: 42, baseline_counts_as_debt: true },
  { invoice_number: "INV-1237", contact_name: "Client 07", reference: "SWF-26091-B-FINBAL", due_date: "2026-08-18", amount_due: 1025.06, line_descriptions: [], line_source: null, job_number: "SWF-26091", job_status: "rectification", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "final", baseline_days_over: 42, baseline_counts_as_debt: true },
  { invoice_number: "INV-1332", contact_name: "Client 08", reference: "SWF-26624-B-BAL", due_date: "2026-08-25", amount_due: 1420.37, line_descriptions: [], line_source: null, job_number: "SWF-26624", job_status: "rectification", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "final", baseline_days_over: 35, baseline_counts_as_debt: true },
  { invoice_number: "INV-0894", contact_name: "Client 09", reference: "SWF-26004-FINBAL", due_date: "2026-09-01", amount_due: 1973.13, line_descriptions: [], line_source: null, job_number: "SWF-26004", job_status: "rectification", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "final", baseline_days_over: 28, baseline_counts_as_debt: true },
  { invoice_number: "INV-1435", contact_name: "Client 10", reference: "SWF-261010-FINBAL50", due_date: "2026-09-02", amount_due: 1056.55, line_descriptions: [], line_source: null, job_number: "SWF-261010", job_status: "archived", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "final", baseline_days_over: 27, baseline_counts_as_debt: true },
  { invoice_number: "INV-1483", contact_name: "Client 11", reference: "SWF-26989-FINBAL50", due_date: "2026-09-07", amount_due: 2433.75, line_descriptions: [], line_source: null, job_number: "SWF-26989", job_status: "invoiced", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "final", baseline_days_over: 22, baseline_counts_as_debt: true },
  { invoice_number: "INV-1191", contact_name: "Client 12", reference: "SWF-26535-B-FINBAL", due_date: "2026-09-21", amount_due: 2101, line_descriptions: [], line_source: null, job_number: "SWF-26535", job_status: "invoiced", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "final", baseline_days_over: 8, baseline_counts_as_debt: true },
  { invoice_number: "INV-1578", contact_name: "Client 13", reference: "SWF-261098-FINBAL", due_date: "2026-09-23", amount_due: 3275.25, line_descriptions: [], line_source: null, job_number: "SWF-261098", job_status: "invoiced", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "final", baseline_days_over: 6, baseline_counts_as_debt: true },
  { invoice_number: "INV-1606", contact_name: "Client 14", reference: "SWF-26168-FINBAL", due_date: "2026-09-29", amount_due: 2653.75, line_descriptions: [], line_source: null, job_number: "SWF-26168", job_status: "invoiced", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "final", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1607", contact_name: "Client 15", reference: "SWP-261046-FINBAL", due_date: "2026-09-29", amount_due: 4086.46, line_descriptions: [], line_source: null, job_number: "SWP-261046", job_status: "invoiced", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "final", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1608", contact_name: "Client 16", reference: "SWP-261183-FINBAL", due_date: "2026-09-29", amount_due: 600, line_descriptions: [], line_source: null, job_number: "SWP-261183", job_status: "complete", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "final", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1609", contact_name: "Client 17", reference: "SWP-26941-FINBAL", due_date: "2026-09-29", amount_due: 9000, line_descriptions: [], line_source: null, job_number: "SWP-26941", job_status: "complete", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "final", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1456", contact_name: "Major Loss Builders", reference: "MLB-25387PO-52385", due_date: "2026-09-13", amount_due: 165, line_descriptions: [], line_source: null, job_number: null, job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "in_dispute", baseline_class: "builder (assessment report)", baseline_days_over: 16, baseline_counts_as_debt: true },
  { invoice_number: "INV-1020", contact_name: "Major Loss Builders", reference: "MLB-26111PO-53991", due_date: "2026-09-28", amount_due: 165, line_descriptions: [], line_source: null, job_number: "SWMS-26732", job_status: "archived", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (assessment report)", baseline_days_over: 1, baseline_counts_as_debt: true },
  { invoice_number: "INV-1557", contact_name: "Major Loss Builders", reference: "MLB-25321PO-52394", due_date: "2026-09-28", amount_due: 165, line_descriptions: [], line_source: null, job_number: null, job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (assessment report)", baseline_days_over: 1, baseline_counts_as_debt: true },
  { invoice_number: "INV-1481", contact_name: "Emergency Trade Services", reference: "PO1479-MS01-001", due_date: "2024-06-19", amount_due: 1028.5, line_descriptions: [], line_source: null, job_number: null, job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "builder (make-safe)", baseline_days_over: 832, baseline_counts_as_debt: true },
  { invoice_number: "INV-0938", contact_name: "Emergency Trade Services", reference: "PO1479-MS01-001", due_date: "2024-06-27", amount_due: 698.5, line_descriptions: [], line_source: null, job_number: null, job_status: null, job_first_payment: null, copy_status: "DELETED", copy_class: null, baseline_class: "builder (make-safe)", baseline_days_over: 824, baseline_counts_as_debt: true },
  { invoice_number: "INV-1424", contact_name: "Emergency Trade Services", reference: "PO9066-MS01-001", due_date: "2025-04-17", amount_due: 720.94, line_descriptions: [], line_source: null, job_number: null, job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "builder (make-safe)", baseline_days_over: 530, baseline_counts_as_debt: true },
  { invoice_number: "INV-1824", contact_name: "Builderwest Pty Ltd ATF Builderwest Unit Trust", reference: "PO19320", due_date: "2025-09-26", amount_due: 418, line_descriptions: [], line_source: null, job_number: null, job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "builder (make-safe)", baseline_days_over: 368, baseline_counts_as_debt: true },
  { invoice_number: "INV-1829", contact_name: "Emergency Trade Services", reference: "PO9066-MS01-001", due_date: "2025-09-26", amount_due: 280.5, line_descriptions: [], line_source: null, job_number: null, job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "builder (make-safe)", baseline_days_over: 368, baseline_counts_as_debt: true },
  { invoice_number: "INV-0352", contact_name: "Insurebuild Pty Ltd WA (AJ Building & Restoration)", reference: "Job 64052", due_date: "2026-04-14", amount_due: 1006.5, line_descriptions: [], line_source: null, job_number: null, job_status: null, job_first_payment: null, copy_status: "DELETED", copy_class: null, baseline_class: "builder (make-safe)", baseline_days_over: 168, baseline_counts_as_debt: true },
  { invoice_number: "INV-0597", contact_name: "Builderwest Pty Ltd", reference: "WB69372", due_date: "2026-06-13", amount_due: 484, line_descriptions: [], line_source: null, job_number: null, job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "builder (make-safe)", baseline_days_over: 108, baseline_counts_as_debt: true },
  { invoice_number: "INV-0562", contact_name: "Western Building Pty Ltd", reference: "WB68792-177207", due_date: "2026-06-17", amount_due: 583, line_descriptions: [], line_source: null, job_number: null, job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 104, baseline_counts_as_debt: true },
  { invoice_number: "INV-0702", contact_name: "Builderwest Pty Ltd", reference: "PO20919", due_date: "2026-06-26", amount_due: 561, line_descriptions: [], line_source: null, job_number: "SWMS-26585", job_status: "archived", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "builder (make-safe)", baseline_days_over: 95, baseline_counts_as_debt: true },
  { invoice_number: "INV-0704", contact_name: "Major Loss Builders", reference: "MLB-25691", due_date: "2026-06-28", amount_due: 561, line_descriptions: [], line_source: null, job_number: null, job_status: "archived", job_first_payment: null, copy_status: "DELETED", copy_class: null, baseline_class: "builder (make-safe)", baseline_days_over: 93, baseline_counts_as_debt: true },
  { invoice_number: "INV-0942", contact_name: "Major Loss Builders", reference: "MLB-23067", due_date: "2026-07-16", amount_due: 563.2, line_descriptions: [], line_source: null, job_number: "SWMS-26845", job_status: "scheduled", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 75, baseline_counts_as_debt: true },
  { invoice_number: "INV-1050", contact_name: "ML Builders", reference: "MLB-27129PO-56730", due_date: "2026-08-06", amount_due: 330, line_descriptions: [], line_source: null, job_number: "SWMS-261028", job_status: "complete", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "builder (make-safe)", baseline_days_over: 54, baseline_counts_as_debt: true },
  { invoice_number: "INV-1181", contact_name: "Major Loss Builders", reference: "MLB-26675PO-58028", due_date: "2026-08-23", amount_due: 617.1, line_descriptions: [], line_source: null, job_number: "SWMS-261156", job_status: "complete", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 37, baseline_counts_as_debt: true },
  { invoice_number: "INV-1274", contact_name: "AJ Building & Restoration", reference: "AJBR-71278", due_date: "2026-09-04", amount_due: 352, line_descriptions: [], line_source: null, job_number: "SWMS-261232", job_status: "processing", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 25, baseline_counts_as_debt: true },
  { invoice_number: "INV-1391", contact_name: "ML Builders", reference: "MLB-27334PO-57651", due_date: "2026-09-04", amount_due: 280.5, line_descriptions: [], line_source: null, job_number: "SWMS-261134", job_status: "complete", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "builder (make-safe)", baseline_days_over: 25, baseline_counts_as_debt: true },
  { invoice_number: "INV-1389", contact_name: "AJ Building & Restoration", reference: "AJBR-70886", due_date: "2026-09-11", amount_due: 176, line_descriptions: [], line_source: null, job_number: "SWMS-261184", job_status: "complete", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 18, baseline_counts_as_debt: true },
  { invoice_number: "INV-1440", contact_name: "Major Loss Builders", reference: "MLB-RR-27899PO-60023", due_date: "2026-09-16", amount_due: 412.5, line_descriptions: [], line_source: null, job_number: "SWMS-261356", job_status: "accepted", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 13, baseline_counts_as_debt: true },
  { invoice_number: "INV-1451", contact_name: "Major Loss Builders", reference: "MLB-28082PO-59913", due_date: "2026-09-17", amount_due: 357.5, line_descriptions: [], line_source: null, job_number: "SWMS-261345", job_status: "processing", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 12, baseline_counts_as_debt: true },
  { invoice_number: "INV-1453", contact_name: "Major Loss Builders", reference: "MLB-28037PO-59734", due_date: "2026-09-17", amount_due: 358.6, line_descriptions: [], line_source: null, job_number: "SWMS-261331", job_status: "processing", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 12, baseline_counts_as_debt: true },
  { invoice_number: "INV-1454", contact_name: "Major Loss Builders", reference: "MLB-25975", due_date: "2026-09-17", amount_due: 1180.3, line_descriptions: [], line_source: null, job_number: "SWMS-26778", job_status: "accepted", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 12, baseline_counts_as_debt: true },
  { invoice_number: "INV-1455", contact_name: "Major Loss Builders", reference: "RR-27221", due_date: "2026-09-17", amount_due: 766.7, line_descriptions: [], line_source: null, job_number: "SWMS-261110", job_status: "processing", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 12, baseline_counts_as_debt: true },
  { invoice_number: "INV-1457", contact_name: "Major Loss Builders", reference: "MLB-27449PO-57869", due_date: "2026-09-17", amount_due: 856.9, line_descriptions: [], line_source: null, job_number: "SWMS-261148", job_status: "processing", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 12, baseline_counts_as_debt: true },
  { invoice_number: "INV-1459", contact_name: "Major Loss Builders", reference: "MLB-25730PO-54171", due_date: "2026-09-17", amount_due: 664.95, line_descriptions: [], line_source: null, job_number: "SWMS-261285", job_status: "processing", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 12, baseline_counts_as_debt: true },
  { invoice_number: "INV-1460", contact_name: "Major Loss Builders", reference: "MLB-28087PO-59928", due_date: "2026-09-17", amount_due: 1572.45, line_descriptions: [], line_source: null, job_number: "SWMS-261348", job_status: "scheduled", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 12, baseline_counts_as_debt: true },
  { invoice_number: "INV-1463", contact_name: "Major Loss Builders", reference: "MLB-25953PO-54269", due_date: "2026-09-17", amount_due: 561, line_descriptions: [], line_source: null, job_number: "SWMS-261272", job_status: "processing", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 12, baseline_counts_as_debt: true },
  { invoice_number: "INV-1474", contact_name: "Major Loss Builders", reference: "MLB-26549PO-55100", due_date: "2026-09-18", amount_due: 638, line_descriptions: [], line_source: null, job_number: "SWMS-26883", job_status: "processing", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 11, baseline_counts_as_debt: true },
  { invoice_number: "INV-1479", contact_name: "Major Loss Builders", reference: "MLB-28064PO-59823", due_date: "2026-09-18", amount_due: 1597.75, line_descriptions: [], line_source: null, job_number: "SWMS-261341", job_status: "processing", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 11, baseline_counts_as_debt: true },
  { invoice_number: "INV-1489", contact_name: "Major Loss Builders", reference: "MLB-28023PO-59630", due_date: "2026-09-18", amount_due: 1028.5, line_descriptions: [], line_source: null, job_number: "SWMS-261393", job_status: "complete", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 11, baseline_counts_as_debt: true },
  { invoice_number: "INV-1495", contact_name: "Major Loss Builders", reference: "MLB-25801", due_date: "2026-09-22", amount_due: 433.4, line_descriptions: [], line_source: null, job_number: "SWMS-26619", job_status: "processing", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 7, baseline_counts_as_debt: true },
  { invoice_number: "INV-1497", contact_name: "Major Loss Builders", reference: "MLB-25826PO-56483", due_date: "2026-09-22", amount_due: 598.4, line_descriptions: [], line_source: null, job_number: "SWMS-261026", job_status: "processing", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 7, baseline_counts_as_debt: true },
  { invoice_number: "INV-1499", contact_name: "Major Loss Builders", reference: "MLB-26537PO-56926", due_date: "2026-09-22", amount_due: 639.1, line_descriptions: [], line_source: null, job_number: "SWMS-261058", job_status: "processing", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 7, baseline_counts_as_debt: true },
  { invoice_number: "INV-1503", contact_name: "Major Loss Builders", reference: "MLB-24267PO-60304", due_date: "2026-09-22", amount_due: 359.7, line_descriptions: [], line_source: null, job_number: "SWMS-261386", job_status: "accepted", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (make-safe)", baseline_days_over: 7, baseline_counts_as_debt: true },
  { invoice_number: "INV-1515", contact_name: "Major Loss Builders", reference: "MLB-40177PO-60526", due_date: "2026-09-24", amount_due: 374, line_descriptions: [], line_source: null, job_number: "SWMS-261403", job_status: "accepted", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (make-safe)", baseline_days_over: 5, baseline_counts_as_debt: true },
  { invoice_number: "INV-1524", contact_name: "Major Loss Builders", reference: "MLB-40182PO-60540", due_date: "2026-09-28", amount_due: 1033.45, line_descriptions: [], line_source: null, job_number: "SWMS-261404", job_status: "accepted", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (make-safe)", baseline_days_over: 1, baseline_counts_as_debt: true },
  { invoice_number: "INV-1534", contact_name: "Major Loss Builders", reference: "MLB-27023PO-RET14", due_date: "2026-09-29", amount_due: 500.5, line_descriptions: [], line_source: null, job_number: "SWMS-261415", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (make-safe)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1558", contact_name: "Major Loss Builders", reference: "MLB-24765", due_date: "2026-10-01", amount_due: 521.4, line_descriptions: [], line_source: null, job_number: "SWMS-26807", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (make-safe)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1560", contact_name: "Major Loss Builders", reference: "MLB-26533PO-55126", due_date: "2026-10-01", amount_due: 600.6, line_descriptions: [], line_source: null, job_number: "SWMS-261450", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (make-safe)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1572", contact_name: "Major Loss Builders", reference: "MLB-27629PO-58256", due_date: "2026-10-02", amount_due: 667.7, line_descriptions: [], line_source: null, job_number: "SWMS-261182", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (make-safe)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1559", contact_name: "Major Loss Builders", reference: "MLB-26442", due_date: "2026-10-05", amount_due: 997.7, line_descriptions: [], line_source: null, job_number: "SWMS-26823", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (make-safe)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1564", contact_name: "Major Loss Builders", reference: "MLB-40337PO-61305", due_date: "2026-10-05", amount_due: 1090.1, line_descriptions: [], line_source: null, job_number: "SWMS-261444", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (make-safe)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1569", contact_name: "Major Loss Builders", reference: "MLB-40059PO-61249", due_date: "2026-10-05", amount_due: 508.2, line_descriptions: [], line_source: null, job_number: "SWMS-261437", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (make-safe)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1570", contact_name: "Major Loss Builders", reference: "MLB-40288PO-61233", due_date: "2026-10-05", amount_due: 310.2, line_descriptions: [], line_source: null, job_number: "SWMS-261433", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (make-safe)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1575", contact_name: "Major Loss Builders", reference: "MLB-40349PO-61387", due_date: "2026-10-06", amount_due: 856.9, line_descriptions: [], line_source: null, job_number: "SWMS-261452", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (make-safe)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1576", contact_name: "Major Loss Builders", reference: "MLB-40339PO-61451", due_date: "2026-10-06", amount_due: 310.2, line_descriptions: [], line_source: null, job_number: "SWMS-261455", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (make-safe)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1584", contact_name: "AJ Building & Restoration", reference: "AJBR-72711", due_date: "2026-10-08", amount_due: 352, line_descriptions: [], line_source: null, job_number: "SWMS-261453", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (make-safe)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1585", contact_name: "Major Loss Builders", reference: "MLB-40329PO-61562", due_date: "2026-10-08", amount_due: 336.6, line_descriptions: [], line_source: null, job_number: "SWMS-261464", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (make-safe)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1587", contact_name: "AJ Building & Restoration", reference: "AJBR-72853", due_date: "2026-10-08", amount_due: 259.6, line_descriptions: [], line_source: null, job_number: "SWMS-261454", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (make-safe)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1594", contact_name: "Major Loss Builders", reference: "MLB-40398PO-61751", due_date: "2026-10-12", amount_due: 650.1, line_descriptions: [], line_source: null, job_number: "SWMS-261476", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (make-safe)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1595", contact_name: "Major Loss Builders", reference: "MLB-40406PO-61746", due_date: "2026-10-12", amount_due: 673.2, line_descriptions: [], line_source: null, job_number: "SWMS-261475", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (make-safe)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1442", contact_name: "Major Loss Builders", reference: "SWF-261281", due_date: "2026-09-02", amount_due: 3718, line_descriptions: [], line_source: null, job_number: "SWF-261281", job_status: "scheduled", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (repair)", baseline_days_over: 27, baseline_counts_as_debt: true },
  { invoice_number: "INV-1419", contact_name: "Major Loss Builders", reference: "MLB-24319PO-56427", due_date: "2026-09-24", amount_due: 5610, line_descriptions: [], line_source: null, job_number: null, job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (repair)", baseline_days_over: 5, baseline_counts_as_debt: true },
  { invoice_number: "INV-1577", contact_name: "Major Loss Builders", reference: "MLB-RR-27649", due_date: "2026-10-03", amount_due: 1386, line_descriptions: [], line_source: null, job_number: null, job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (repair)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1580", contact_name: "Major Loss Builders", reference: "MLB-26640PO-59061", due_date: "2026-10-05", amount_due: 2145, line_descriptions: [], line_source: null, job_number: "SWF-261280", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (repair)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1591", contact_name: "Major Loss Builders", reference: "MLB-22280PO-61535", due_date: "2026-10-06", amount_due: 605, line_descriptions: [], line_source: null, job_number: "SWMS-261462", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (repair)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-0857", contact_name: "Major Loss Builders", reference: "MLB-25897 - Roof Report", due_date: "2026-07-16", amount_due: 275, line_descriptions: [], line_source: null, job_number: "SWMS-26814", job_status: "processing", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (roof report)", baseline_days_over: 75, baseline_counts_as_debt: true },
  { invoice_number: "INV-1018", contact_name: "Major Loss Builders", reference: "MLB-26533PO-54950", due_date: "2026-08-04", amount_due: 385, line_descriptions: [], line_source: null, job_number: "SWMS-26865", job_status: "archived", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (roof report)", baseline_days_over: 56, baseline_counts_as_debt: true },
  { invoice_number: "INV-1149", contact_name: "Major Loss Builders", reference: "RR-26836", due_date: "2026-08-20", amount_due: 330, line_descriptions: [], line_source: null, job_number: "SWMS-261114", job_status: "accepted", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (roof report)", baseline_days_over: 40, baseline_counts_as_debt: true },
  { invoice_number: "INV-1381", contact_name: "Major Loss Builders", reference: "MLB-25986", due_date: "2026-09-11", amount_due: 275, line_descriptions: [], line_source: null, job_number: "SWMS-26715", job_status: "processing", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (roof report)", baseline_days_over: 18, baseline_counts_as_debt: true },
  { invoice_number: "INV-1384", contact_name: "Major Loss Builders", reference: "MLB-26380", due_date: "2026-09-11", amount_due: 330, line_descriptions: [], line_source: null, job_number: "SWMS-26810", job_status: "processing", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (roof report)", baseline_days_over: 18, baseline_counts_as_debt: true },
  { invoice_number: "INV-1446", contact_name: "Major Loss Builders", reference: "MLB-RR-27899PO-59835", due_date: "2026-09-17", amount_due: 275, line_descriptions: [], line_source: null, job_number: "SWMS-261342", job_status: "accepted", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (roof report)", baseline_days_over: 12, baseline_counts_as_debt: true },
  { invoice_number: "INV-1447", contact_name: "Major Loss Builders", reference: "MLB-19475PO-57512", due_date: "2026-09-17", amount_due: 275, line_descriptions: [], line_source: null, job_number: "SWMS-261113", job_status: "processing", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (roof report)", baseline_days_over: 12, baseline_counts_as_debt: true },
  { invoice_number: "INV-1449", contact_name: "Major Loss Builders", reference: "MLB-27968PO-60081", due_date: "2026-09-17", amount_due: 275, line_descriptions: [], line_source: null, job_number: "SWMS-261358", job_status: "accepted", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (roof report)", baseline_days_over: 12, baseline_counts_as_debt: true },
  { invoice_number: "INV-1505", contact_name: "Major Loss Builders", reference: "MLB-40131PO-60353", due_date: "2026-09-22", amount_due: 275, line_descriptions: [], line_source: null, job_number: "SWMS-261391", job_status: "scheduled", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (roof report)", baseline_days_over: 7, baseline_counts_as_debt: true },
  { invoice_number: "INV-1506", contact_name: "Major Loss Builders", reference: "MLB-40100PO-60319", due_date: "2026-09-22", amount_due: 275, line_descriptions: [], line_source: null, job_number: "SWMS-261389", job_status: "accepted", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (roof report)", baseline_days_over: 7, baseline_counts_as_debt: true },
  { invoice_number: "INV-1507", contact_name: "Major Loss Builders", reference: "MLB-40055PO-60207", due_date: "2026-09-22", amount_due: 330, line_descriptions: [], line_source: null, job_number: "SWMS-261368", job_status: "scheduled", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (roof report)", baseline_days_over: 7, baseline_counts_as_debt: true },
  { invoice_number: "INV-1509", contact_name: "Major Loss Builders", reference: "MLB-RR-27871PO-59316", due_date: "2026-09-22", amount_due: 275, line_descriptions: [], line_source: null, job_number: "SWMS-261298", job_status: "processing", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (roof report)", baseline_days_over: 7, baseline_counts_as_debt: true },
  { invoice_number: "INV-1510", contact_name: "Major Loss Builders", reference: "MLB-40084PO-60272", due_date: "2026-09-22", amount_due: 275, line_descriptions: [], line_source: null, job_number: "SWMS-261373", job_status: "accepted", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (roof report)", baseline_days_over: 7, baseline_counts_as_debt: true },
  { invoice_number: "INV-1514", contact_name: "Major Loss Builders", reference: "MLB-24267PO-59506", due_date: "2026-09-24", amount_due: 275, line_descriptions: [], line_source: null, job_number: "SWMS-261313", job_status: "accepted", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (roof report)", baseline_days_over: 5, baseline_counts_as_debt: true },
  { invoice_number: "INV-1561", contact_name: "Major Loss Builders", reference: "MLB-40293PO-61231", due_date: "2026-10-05", amount_due: 275, line_descriptions: [], line_source: null, job_number: "SWMS-261432", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (roof report)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1562", contact_name: "Major Loss Builders", reference: "MLB-40059PO-61248", due_date: "2026-10-05", amount_due: 275, line_descriptions: [], line_source: null, job_number: "SWMS-261436", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (roof report)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1568", contact_name: "Major Loss Builders", reference: "MLB-40268PO-60930", due_date: "2026-10-05", amount_due: 385, line_descriptions: [], line_source: null, job_number: "SWMS-261420", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (roof report)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1579", contact_name: "Major Loss Builders", reference: "MLB-40339PO-61327", due_date: "2026-10-07", amount_due: 275, line_descriptions: [], line_source: null, job_number: "SWMS-261447", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (roof report)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1582", contact_name: "Major Loss Builders", reference: "MLB-40147PO-61349", due_date: "2026-10-07", amount_due: 275, line_descriptions: [], line_source: null, job_number: "SWMS-261449", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (roof report)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1583", contact_name: "Major Loss Builders", reference: "MLB-40329PO-61262", due_date: "2026-10-08", amount_due: 275, line_descriptions: [], line_source: null, job_number: "SWMS-261440", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (roof report)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1592", contact_name: "Major Loss Builders", reference: "MLB-40406PO-61581", due_date: "2026-10-09", amount_due: 275, line_descriptions: [], line_source: null, job_number: "SWMS-261467", job_status: null, job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "builder (roof report)", baseline_days_over: 0, baseline_counts_as_debt: true },
  { invoice_number: "INV-1240", contact_name: "AJ Building & Restoration", reference: "SAMPLE-AJS-WALK-1", due_date: "2026-09-01", amount_due: 352, line_descriptions: [], line_source: null, job_number: "SWMS-261237", job_status: "cancelled", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "builder (test/sample record)", baseline_days_over: 28, baseline_counts_as_debt: false },
  { invoice_number: "INV-0560", contact_name: "Client 18", reference: "SWF-26451-DEP50", due_date: "2026-06-18", amount_due: 53.14, line_descriptions: [], line_source: null, job_number: "SWF-26451", job_status: "archived", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "not_owed", baseline_class: "deposit", baseline_days_over: 103, baseline_counts_as_debt: false },
  { invoice_number: "INV-1010", contact_name: "Client 19", reference: "SWP-26992-DEP20", due_date: "2026-07-23", amount_due: 770, line_descriptions: [], line_source: null, job_number: "SWP-26992", job_status: "order_materials", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "deposit", baseline_days_over: 68, baseline_counts_as_debt: false },
  { invoice_number: "INV-1011", contact_name: "Client 20", reference: "SWP-26354-DEP25", due_date: "2026-07-30", amount_due: 1480, line_descriptions: [], line_source: null, job_number: "SWP-26354", job_status: "rectification", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "deposit", baseline_days_over: 61, baseline_counts_as_debt: false },
  { invoice_number: "INV-1119", contact_name: "Client 21", reference: "SWF-26984-C-RHS-DEP50", due_date: "2026-08-09", amount_due: 2052.88, line_descriptions: [], line_source: null, job_number: "SWF-26984", job_status: "archived", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "deposit", baseline_days_over: 51, baseline_counts_as_debt: false },
  { invoice_number: "INV-1374", contact_name: "Client 22", reference: "SWF-261227-B-DEP50", due_date: "2026-09-11", amount_due: 840.13, line_descriptions: [], line_source: null, job_number: "SWF-261227", job_status: "processing", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "blocked_by_us", baseline_class: "deposit", baseline_days_over: 18, baseline_counts_as_debt: false },
  { invoice_number: "INV-1571", contact_name: "Client 23", reference: "SWF-261306-DEP50", due_date: "2026-10-06", amount_due: 633.88, line_descriptions: [], line_source: null, job_number: "SWF-261306", job_status: "awaiting_deposit", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "deposit", baseline_days_over: 0, baseline_counts_as_debt: false },
  { invoice_number: "INV-1601", contact_name: "Client 14", reference: "JOB-DEP", due_date: "2026-10-06", amount_due: 2653.75, line_descriptions: [], line_source: null, job_number: "SWF-26168", job_status: "invoiced", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "deposit", baseline_days_over: 0, baseline_counts_as_debt: false },
  { invoice_number: "INV-1602", contact_name: "Client 24", reference: "DEP50", due_date: "2026-10-06", amount_due: 1018.18, line_descriptions: [], line_source: null, job_number: "SWF-261371", job_status: "draft", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "deposit", baseline_days_over: 0, baseline_counts_as_debt: false },
  { invoice_number: "INV-1603", contact_name: "Client 25", reference: "DEP50", due_date: "2026-10-06", amount_due: 1018, line_descriptions: [], line_source: null, job_number: "SWF-261335", job_status: "invoiced", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "deposit", baseline_days_over: 0, baseline_counts_as_debt: false },
  { invoice_number: "INV-1597", contact_name: "Client 26", reference: "SWF-261481-DEP50", due_date: "2026-10-13", amount_due: 302.51, line_descriptions: [], line_source: null, job_number: "SWF-261481", job_status: "accepted", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "unclassified", baseline_class: "deposit", baseline_days_over: 0, baseline_counts_as_debt: false },
  { invoice_number: "INV-1477", contact_name: "Client 27", reference: "SWP-261247-PROG", due_date: "2026-09-11", amount_due: 10319.68, line_descriptions: [], line_source: null, job_number: "SWP-261247", job_status: "draft", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "progress claim", baseline_days_over: 18, baseline_counts_as_debt: false },
  { invoice_number: "INV-0080", contact_name: "Client 14", reference: "", due_date: "2025-11-20", amount_due: 231, line_descriptions: ["Extra Labour and Material"], line_source: "debt-baseline-s2 section 3.1: the only no-reference invoice classed variation by the line \"Extra Labour and Material\"", job_number: null, job_status: "cancelled", job_first_payment: null, copy_status: "DELETED", copy_class: null, baseline_class: "variation", baseline_days_over: 313, baseline_counts_as_debt: false },
  { invoice_number: "INV-0034", contact_name: "Client 28", reference: "", due_date: "2025-10-30", amount_due: 734.48, line_descriptions: [], line_source: null, job_number: null, job_status: "complete", job_first_payment: null, copy_status: "DELETED", copy_class: null, baseline_class: "unclear (legacy % of quote)", baseline_days_over: 334, baseline_counts_as_debt: false },
  { invoice_number: "INV-0177", contact_name: "Client 29", reference: "", due_date: "2026-01-19", amount_due: 352, line_descriptions: [], line_source: null, job_number: null, job_status: "complete", job_first_payment: null, copy_status: "DELETED", copy_class: null, baseline_class: "unclear (legacy % of quote)", baseline_days_over: 253, baseline_counts_as_debt: false },
  { invoice_number: "INV-0267", contact_name: "Client 04", reference: "F-FD-Q1-SK-NI", due_date: "2026-04-02", amount_due: 839.2, line_descriptions: [], line_source: null, job_number: "SWF-26282", job_status: "final_payment", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "unclear (legacy % of quote)", baseline_days_over: 180, baseline_counts_as_debt: false },
  { invoice_number: "INV-1486", contact_name: "Client 30", reference: "SWP-261377-PLAN", due_date: "2026-09-14", amount_due: 1500, line_descriptions: [], line_source: null, job_number: "SWP-261377", job_status: "draft", job_first_payment: null, copy_status: "AUTHORISED", copy_class: "genuine_debt", baseline_class: "unclear (planning fee)", baseline_days_over: 15, baseline_counts_as_debt: false },
]
