-- Make-safe state-authority seed scope correction.
--
-- The canonical board contains both ordinary make-safe jobs and the explicitly
-- typed insurance/restoration family. The original seed RPC accepted only
-- jobs.type='makesafe', so a truthful full-board selection could never seed.
--
-- This migration is schema/RPC only. It does not run the seed, mutate a board
-- status, send a communication, or touch a financial record.

DO $migration$
DECLARE
  v_definition text;
  v_old_guard text := 'AND j.type = ''makesafe'';';
  v_new_guard text :=
    'AND (j.type = ''makesafe'' OR (j.type = ''insurance'' AND j.metadata->>''insurance_job_type'' = ''restoration''));';
  v_occurrences integer;
BEGIN
  SELECT pg_get_functiondef(
    'public.seed_makesafe_state_authority_v1(text,text,text,uuid[])'::regprocedure
  )
  INTO STRICT v_definition;

  IF strpos(v_definition, v_new_guard) > 0 THEN
    RETURN;
  END IF;

  v_occurrences := (
    length(v_definition) - length(replace(v_definition, v_old_guard, ''))
  ) / length(v_old_guard);
  IF v_occurrences <> 1 THEN
    RAISE EXCEPTION
      'seed scope migration expected exactly one legacy make-safe guard, found %',
      v_occurrences;
  END IF;

  EXECUTE replace(v_definition, v_old_guard, v_new_guard);
END;
$migration$;

DO $migration$
DECLARE
  v_definition text;
  v_old_guard text := 'j.id = NEW.job_id AND j.type = ''makesafe''';
  v_new_guard text :=
    'j.id = NEW.job_id AND (j.type = ''makesafe'' OR (j.type = ''insurance'' AND j.metadata->>''insurance_job_type'' = ''restoration''))';
  v_occurrences integer;
BEGIN
  SELECT pg_get_functiondef(
    'public.stamp_makesafe_fact_identity_v1()'::regprocedure
  )
  INTO STRICT v_definition;

  IF strpos(v_definition, v_new_guard) > 0 THEN
    RETURN;
  END IF;

  v_occurrences := (
    length(v_definition) - length(replace(v_definition, v_old_guard, ''))
  ) / length(v_old_guard);
  IF v_occurrences <> 1 THEN
    RAISE EXCEPTION
      'fact identity migration expected exactly one legacy make-safe guard, found %',
      v_occurrences;
  END IF;

  EXECUTE replace(v_definition, v_old_guard, v_new_guard);
END;
$migration$;

CREATE TABLE IF NOT EXISTS public.makesafe_state_seed_scope_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_key text NOT NULL UNIQUE
    CHECK (length(btrim(run_key)) BETWEEN 1 AND 160),
  selection_hash text NOT NULL
    CHECK (selection_hash ~ '^sha256:[0-9a-f]{64}$'),
  scope_hash text NOT NULL
    CHECK (scope_hash ~ '^sha256:[0-9a-f]{64}$'),
  requested_count integer NOT NULL CHECK (requested_count BETWEEN 1 AND 500),
  seeded_count integer NOT NULL CHECK (
    seeded_count BETWEEN 0 AND requested_count
  ),
  skipped_missing_count integer NOT NULL CHECK (
    skipped_missing_count BETWEEN 0 AND requested_count
  ),
  skipped_out_of_scope_count integer NOT NULL CHECK (
    skipped_out_of_scope_count BETWEEN 0 AND requested_count
  ),
  result_json jsonb NOT NULL CHECK (jsonb_typeof(result_json) = 'object'),
  applied_by text NOT NULL CHECK (length(btrim(applied_by)) > 0),
  applied_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT makesafe_state_seed_scope_partition_check CHECK (
    seeded_count + skipped_missing_count + skipped_out_of_scope_count =
      requested_count
  )
);

COMMENT ON TABLE public.makesafe_state_seed_scope_runs IS
  'Append-only, per-chunk seed scope ledger. Every server-selected board job is recorded as seeded, missing after the board read, or outside the canonical make-safe/restoration scope.';

DROP TRIGGER IF EXISTS trg_makesafe_state_seed_scope_runs_append_only
  ON public.makesafe_state_seed_scope_runs;
CREATE TRIGGER trg_makesafe_state_seed_scope_runs_append_only
  BEFORE UPDATE OR DELETE ON public.makesafe_state_seed_scope_runs
  FOR EACH ROW EXECUTE FUNCTION public.reject_makesafe_state_seed_audit_mutation();

CREATE OR REPLACE FUNCTION public.seed_makesafe_state_authority_scoped_v2(
  p_run_key text,
  p_applied_by text,
  p_selection_hash text,
  p_job_ids uuid[]
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, extensions
AS $$
DECLARE
  v_requested integer;
  v_scope_hash text;
  v_eligible_job_ids uuid[];
  v_missing_job_ids uuid[];
  v_out_of_scope_jobs jsonb;
  v_seeded integer;
  v_missing integer;
  v_out_of_scope integer;
  v_seed_result jsonb;
  v_result jsonb;
  v_existing public.makesafe_state_seed_scope_runs%ROWTYPE;
BEGIN
  IF length(btrim(COALESCE(p_run_key, ''))) = 0
     OR length(btrim(COALESCE(p_applied_by, ''))) = 0
     OR COALESCE(p_selection_hash, '') !~ '^sha256:[0-9a-f]{64}$' THEN
    RAISE EXCEPTION
      'run key, attribution, and sha256 selection hash are required';
  END IF;

  v_requested := cardinality(p_job_ids);
  IF v_requested < 1 OR v_requested > 500 THEN
    RAISE EXCEPTION 'p_job_ids must contain between 1 and 500 jobs';
  END IF;
  IF v_requested <> (
    SELECT count(DISTINCT id) FROM unnest(p_job_ids) ids(id)
  ) THEN
    RAISE EXCEPTION 'p_job_ids contains duplicate jobs';
  END IF;

  SELECT 'sha256:' || encode(
    extensions.digest(
      convert_to(
        (
          SELECT string_agg(id::text, ',' ORDER BY id)
          FROM unnest(p_job_ids) ids(id)
        ),
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  )
  INTO v_scope_hash;

  PERFORM pg_advisory_xact_lock(
    hashtext('makesafe_state_seed_scope_v2'),
    hashtext(p_run_key)
  );

  SELECT * INTO v_existing
  FROM public.makesafe_state_seed_scope_runs
  WHERE run_key = p_run_key;
  IF FOUND THEN
    IF v_existing.selection_hash IS DISTINCT FROM p_selection_hash
       OR v_existing.scope_hash IS DISTINCT FROM v_scope_hash THEN
      RAISE EXCEPTION
        'seed scope run key already belongs to a different selection';
    END IF;
    RETURN v_existing.result_json ||
      jsonb_build_object('idempotent_replay', true);
  END IF;

  -- Keep the classification stable until the nested seed finishes. Missing
  -- rows cannot be locked, but every existing candidate is protected from a
  -- concurrent type/metadata change or delete for this transaction.
  PERFORM j.id
  FROM public.jobs j
  WHERE j.id = ANY(p_job_ids)
  ORDER BY j.id
  FOR SHARE;

  WITH requested AS (
    SELECT id
    FROM unnest(p_job_ids) ids(id)
  ),
  classified AS (
    SELECT
      r.id AS requested_id,
      j.id AS found_id,
      j.type AS observed_type,
      j.metadata->>'insurance_job_type' AS observed_insurance_job_type,
      (
        j.type = 'makesafe'
        OR (
          j.type = 'insurance'
          AND j.metadata->>'insurance_job_type' = 'restoration'
        )
      ) AS is_canonical_makesafe
    FROM requested r
    LEFT JOIN public.jobs j ON j.id = r.id
  )
  SELECT
    COALESCE(
      array_agg(requested_id ORDER BY requested_id)
        FILTER (
          WHERE found_id IS NOT NULL
            AND COALESCE(is_canonical_makesafe, false)
        ),
      ARRAY[]::uuid[]
    ),
    COALESCE(
      array_agg(requested_id ORDER BY requested_id)
        FILTER (WHERE found_id IS NULL),
      ARRAY[]::uuid[]
    ),
    COALESCE(
      jsonb_agg(
        jsonb_build_object(
          'job_id', requested_id,
          'reason_code', 'not_canonical_makesafe_job',
          'observed_type', observed_type,
          'observed_insurance_job_type', observed_insurance_job_type
        )
        ORDER BY requested_id
      ) FILTER (
        WHERE found_id IS NOT NULL
          AND NOT COALESCE(is_canonical_makesafe, false)
      ),
      '[]'::jsonb
    )
  INTO
    v_eligible_job_ids,
    v_missing_job_ids,
    v_out_of_scope_jobs
  FROM classified;

  v_seeded := cardinality(v_eligible_job_ids);
  v_missing := cardinality(v_missing_job_ids);
  v_out_of_scope := jsonb_array_length(v_out_of_scope_jobs);
  IF v_seeded + v_missing + v_out_of_scope <> v_requested THEN
    RAISE EXCEPTION
      'seed scope did not partition every requested job exactly once';
  END IF;

  IF v_seeded > 0 THEN
    v_seed_result := public.seed_makesafe_state_authority_v1(
      p_run_key,
      p_applied_by,
      p_selection_hash,
      v_eligible_job_ids
    );
    IF COALESCE((v_seed_result->>'requested')::integer, -1) <> v_seeded THEN
      RAISE EXCEPTION
        'nested seed did not account for the exact eligible scope';
    END IF;
  ELSE
    v_seed_result := jsonb_build_object(
      'ok', true,
      'run_key', p_run_key,
      'selection_hash', p_selection_hash,
      'requested', 0,
      'identity_revisions_inserted', 0,
      'attendance_cycles_created', 0,
      'facts_seeded_or_bound', 0,
      'family_resolved', 0,
      'family_unresolved', 0,
      'terminal_proofs_inserted', 0,
      'cancellations_inserted', 0,
      'idempotent_replay', false
    );
  END IF;

  v_result := jsonb_build_object(
    'ok', true,
    'run_key', p_run_key,
    'selection_hash', p_selection_hash,
    'scope_hash', v_scope_hash,
    'requested', v_requested,
    'accounted', v_requested,
    'seeded', v_seeded,
    'skipped', v_missing + v_out_of_scope,
    'skipped_missing_count', v_missing,
    'skipped_missing_job_ids', to_jsonb(v_missing_job_ids),
    'skipped_out_of_scope_count', v_out_of_scope,
    'skipped_out_of_scope_jobs', v_out_of_scope_jobs,
    'seed_result', v_seed_result,
    'idempotent_replay', false
  );

  INSERT INTO public.makesafe_state_seed_scope_runs (
    run_key,
    selection_hash,
    scope_hash,
    requested_count,
    seeded_count,
    skipped_missing_count,
    skipped_out_of_scope_count,
    result_json,
    applied_by
  ) VALUES (
    p_run_key,
    p_selection_hash,
    v_scope_hash,
    v_requested,
    v_seeded,
    v_missing,
    v_out_of_scope,
    v_result,
    p_applied_by
  );

  RETURN v_result;
END;
$$;

ALTER TABLE public.makesafe_state_seed_scope_runs ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.makesafe_state_seed_scope_runs
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.seed_makesafe_state_authority_scoped_v2(
  text, text, text, uuid[]
) FROM PUBLIC, anon, authenticated, service_role;

GRANT SELECT, INSERT ON public.makesafe_state_seed_scope_runs TO service_role;
GRANT USAGE, SELECT ON SEQUENCE
  public.makesafe_state_seed_scope_runs_id_seq TO service_role;
GRANT EXECUTE ON FUNCTION public.seed_makesafe_state_authority_scoped_v2(
  text, text, text, uuid[]
) TO service_role;

DROP POLICY IF EXISTS service_role_read_makesafe_state_seed_scope_runs
  ON public.makesafe_state_seed_scope_runs;
CREATE POLICY service_role_read_makesafe_state_seed_scope_runs
  ON public.makesafe_state_seed_scope_runs
  FOR SELECT TO service_role USING (true);

DROP POLICY IF EXISTS service_role_insert_makesafe_state_seed_scope_runs
  ON public.makesafe_state_seed_scope_runs;
CREATE POLICY service_role_insert_makesafe_state_seed_scope_runs
  ON public.makesafe_state_seed_scope_runs
  FOR INSERT TO service_role WITH CHECK (true);
