-- Captain-approved MakeSafe board display cutover.
--
-- The application ledger is the display overlay and the durable transition log.
-- It deliberately does NOT update jobs, makesafe_job_details, assignments,
-- invoices, events, communications, or notifications.

CREATE TABLE IF NOT EXISTS public.makesafe_board_status_applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_key text NOT NULL CHECK (length(btrim(run_key)) BETWEEN 1 AND 160),
  job_id uuid NOT NULL REFERENCES public.jobs(id) ON DELETE RESTRICT,
  job_number text NOT NULL CHECK (length(btrim(job_number)) > 0),
  source_status text NOT NULL CHECK (source_status IN (
    'new', 'allocated', 'trade_report_in', 'report_ready'
  )),
  before_status text NOT NULL CHECK (before_status IN (
    'new', 'allocated', 'trade_report_in', 'report_ready'
  )),
  after_status text NOT NULL CHECK (after_status IN (
    'new', 'allocated', 'trade_report_in', 'report_ready',
    'completed', 'archive', 'cancelled'
  )),
  computed_at timestamptz NOT NULL,
  computed_reasons jsonb NOT NULL DEFAULT '[]'::jsonb
    CHECK (
      jsonb_typeof(computed_reasons) = 'array'
      AND jsonb_array_length(computed_reasons) > 0
    ),
  computed_missing jsonb NOT NULL DEFAULT '[]'::jsonb
    CHECK (jsonb_typeof(computed_missing) = 'array'),
  evidence_ref text NOT NULL CHECK (length(btrim(evidence_ref)) > 0),
  applied_by text NOT NULL CHECK (length(btrim(applied_by)) > 0),
  applied_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT makesafe_board_status_applications_changed_check
    CHECK (before_status <> after_status),
  CONSTRAINT makesafe_board_status_applications_idempotency
    UNIQUE (run_key, job_id)
);

CREATE INDEX IF NOT EXISTS idx_makesafe_board_status_applications_current
  ON public.makesafe_board_status_applications (job_id, applied_at DESC, id DESC);

COMMENT ON TABLE public.makesafe_board_status_applications IS
  'Append-only captain-approved MakeSafe display transitions. This is both the board overlay and the durable before/after/evidence audit; it never mutates operational job state.';

ALTER TABLE public.makesafe_board_status_applications ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.makesafe_board_status_applications FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT ON public.makesafe_board_status_applications TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.makesafe_board_status_applications_id_seq TO service_role;
DROP POLICY IF EXISTS service_role_read_makesafe_board_status_applications
  ON public.makesafe_board_status_applications;
CREATE POLICY service_role_read_makesafe_board_status_applications
  ON public.makesafe_board_status_applications FOR SELECT TO service_role
  USING (true);
DROP POLICY IF EXISTS service_role_insert_makesafe_board_status_applications
  ON public.makesafe_board_status_applications;
CREATE POLICY service_role_insert_makesafe_board_status_applications
  ON public.makesafe_board_status_applications FOR INSERT TO service_role
  WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.guard_makesafe_board_status_application_insert()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  current_job_status text;
  current_job_type text;
  current_job_number text;
BEGIN
  SELECT lower(COALESCE(status, '')), type, job_number
  INTO current_job_status, current_job_type, current_job_number
  FROM public.jobs
  WHERE id = NEW.job_id;

  IF NOT FOUND
     OR current_job_type <> 'makesafe'
     OR current_job_number <> NEW.job_number THEN
    RAISE EXCEPTION 'status application job identity is not a current make-safe';
  END IF;
  IF current_job_status IN (
    'archived', 'complete', 'completed', 'closed',
    'cancelled', 'canceled', 'lost', 'deleted'
  ) THEN
    RAISE EXCEPTION 'terminal make-safe jobs are read-only';
  END IF;
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.guard_makesafe_board_status_application_insert()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS trg_makesafe_board_status_applications_insert_guard
  ON public.makesafe_board_status_applications;
CREATE TRIGGER trg_makesafe_board_status_applications_insert_guard
  BEFORE INSERT ON public.makesafe_board_status_applications
  FOR EACH ROW EXECUTE FUNCTION public.guard_makesafe_board_status_application_insert();

CREATE OR REPLACE FUNCTION public.reject_makesafe_board_status_application_mutation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  RAISE EXCEPTION 'makesafe_board_status_applications is append-only';
END;
$$;
REVOKE ALL ON FUNCTION public.reject_makesafe_board_status_application_mutation()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS trg_makesafe_board_status_applications_append_only
  ON public.makesafe_board_status_applications;
CREATE TRIGGER trg_makesafe_board_status_applications_append_only
  BEFORE UPDATE OR DELETE ON public.makesafe_board_status_applications
  FOR EACH ROW EXECUTE FUNCTION public.reject_makesafe_board_status_application_mutation();

CREATE OR REPLACE VIEW public.makesafe_board_status_current
WITH (security_invoker = true)
AS
SELECT DISTINCT ON (job_id)
  id,
  run_key,
  job_id,
  job_number,
  source_status,
  before_status,
  after_status,
  computed_at,
  computed_reasons,
  computed_missing,
  evidence_ref,
  applied_by,
  applied_at
FROM public.makesafe_board_status_applications
ORDER BY job_id, applied_at DESC, id DESC;

REVOKE ALL ON public.makesafe_board_status_current FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.makesafe_board_status_current TO service_role;
COMMENT ON VIEW public.makesafe_board_status_current IS
  'Latest captain-applied display transition per MakeSafe job. The edge read model applies it only while source_status still matches the current declared board stage.';

CREATE OR REPLACE FUNCTION public.apply_makesafe_board_status(
  p_run_key text,
  p_applied_by text,
  p_evidence_ref text,
  p_rows jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  expected_count integer;
  eligible_count integer;
  inserted_count integer;
  applied_rows jsonb;
BEGIN
  IF length(btrim(COALESCE(p_run_key, ''))) = 0
     OR length(btrim(COALESCE(p_applied_by, ''))) = 0
     OR length(btrim(COALESCE(p_evidence_ref, ''))) = 0 THEN
    RAISE EXCEPTION 'run key, attribution, and evidence reference are required';
  END IF;
  IF jsonb_typeof(p_rows) <> 'array' THEN
    RAISE EXCEPTION 'p_rows must be a JSON array';
  END IF;

  expected_count := jsonb_array_length(p_rows);
  IF expected_count < 1 OR expected_count > 500 THEN
    RAISE EXCEPTION 'p_rows must contain between 1 and 500 transitions';
  END IF;

  WITH incoming AS (
    SELECT *
    FROM jsonb_to_recordset(p_rows) AS x(
      job_id uuid,
      job_number text,
      source_status text,
      before_status text,
      after_status text,
      computed_at timestamptz,
      computed_reasons jsonb,
      computed_missing jsonb
    )
  ),
  eligible AS (
    SELECT i.*
    FROM incoming i
    JOIN public.jobs j
      ON j.id = i.job_id
     AND j.job_number = i.job_number
     AND j.type = 'makesafe'
    JOIN public.makesafe_job_details d ON d.job_id = i.job_id
    LEFT JOIN LATERAL (
      SELECT a.after_status
      FROM public.makesafe_board_status_applications a
      WHERE a.job_id = i.job_id
        AND a.source_status = i.source_status
      ORDER BY a.applied_at DESC, a.id DESC
      LIMIT 1
    ) latest ON true
    WHERE lower(COALESCE(j.status, '')) NOT IN (
      'archived', 'complete', 'completed', 'closed',
      'cancelled', 'canceled', 'lost', 'deleted'
    )
      AND i.source_status IN ('new', 'allocated', 'trade_report_in', 'report_ready')
      AND i.before_status IN ('new', 'allocated', 'trade_report_in', 'report_ready')
      AND i.after_status IN (
        'new', 'allocated', 'trade_report_in', 'report_ready',
        'completed', 'archive', 'cancelled'
      )
      AND i.before_status <> i.after_status
      AND i.computed_at IS NOT NULL
      AND jsonb_typeof(COALESCE(i.computed_reasons, '[]'::jsonb)) = 'array'
      AND jsonb_array_length(COALESCE(i.computed_reasons, '[]'::jsonb)) > 0
      AND jsonb_typeof(COALESCE(i.computed_missing, '[]'::jsonb)) = 'array'
      AND COALESCE(latest.after_status, i.source_status) = i.before_status
  )
  SELECT count(*) INTO eligible_count FROM eligible;

  IF eligible_count <> expected_count THEN
    RAISE EXCEPTION
      'guarded apply rejected one or more transitions (expected %, eligible %)',
      expected_count, eligible_count;
  END IF;

  WITH incoming AS (
    SELECT *
    FROM jsonb_to_recordset(p_rows) AS x(
      job_id uuid,
      job_number text,
      source_status text,
      before_status text,
      after_status text,
      computed_at timestamptz,
      computed_reasons jsonb,
      computed_missing jsonb
    )
  ),
  inserted AS (
    INSERT INTO public.makesafe_board_status_applications (
      run_key,
      job_id,
      job_number,
      source_status,
      before_status,
      after_status,
      computed_at,
      computed_reasons,
      computed_missing,
      evidence_ref,
      applied_by
    )
    SELECT
      p_run_key,
      i.job_id,
      i.job_number,
      i.source_status,
      i.before_status,
      i.after_status,
      i.computed_at,
      COALESCE(i.computed_reasons, '[]'::jsonb),
      COALESCE(i.computed_missing, '[]'::jsonb),
      p_evidence_ref,
      p_applied_by
    FROM incoming i
    ON CONFLICT (run_key, job_id) DO NOTHING
    RETURNING *
  )
  SELECT count(*), COALESCE(jsonb_agg(to_jsonb(inserted) ORDER BY id), '[]'::jsonb)
  INTO inserted_count, applied_rows
  FROM inserted;

  IF inserted_count <> expected_count THEN
    RAISE EXCEPTION
      'run key already exists with a conflicting or partial transition set';
  END IF;

  RETURN jsonb_build_object(
    'run_key', p_run_key,
    'applied_count', inserted_count,
    'applied', applied_rows
  );
END;
$$;

REVOKE ALL ON FUNCTION public.apply_makesafe_board_status(text, text, text, jsonb)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.apply_makesafe_board_status(text, text, text, jsonb)
  TO service_role;
COMMENT ON FUNCTION public.apply_makesafe_board_status(text, text, text, jsonb) IS
  'Atomic idempotency-keyed display-only MakeSafe status application. Rejects terminal job states and stale plans; appends a complete before/after/evidence audit without invoking operational writers.';
