-- SES Reporting U2: atomic board reconciliation plus visible Captain actions.
--
-- SCHEMA/RPC ONLY. This migration performs no data backfill, no authority flip,
-- and no operational status/substatus mutation. The privileged edge action is
-- dark by default and is not invoked by this PR.

CREATE TABLE IF NOT EXISTS public.makesafe_state_identity_revisions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  job_id uuid NOT NULL REFERENCES public.jobs(id) ON DELETE RESTRICT,
  authority_kind text NOT NULL CHECK (authority_kind IN (
    'effective_intake_case', 'legacy_job_record', 'unresolved_authority'
  )),
  effective_case_id uuid
    REFERENCES public.makesafe_intake_cases(id) ON DELETE RESTRICT,
  source_instruction_id text NOT NULL
    CHECK (length(btrim(source_instruction_id)) > 0),
  source_version bigint NOT NULL CHECK (source_version > 0),
  source_content_hash text NOT NULL
    CHECK (source_content_hash ~ '^sha256:[0-9a-f]{64}$'),
  lineage_id text NOT NULL CHECK (length(btrim(lineage_id)) > 0),
  lineage_version bigint NOT NULL CHECK (lineage_version > 0),
  lineage_correction_hash text NOT NULL
    CHECK (lineage_correction_hash ~ '^sha256:[0-9a-f]{64}$'),
  lineage_supersession_hash text NOT NULL
    CHECK (lineage_supersession_hash ~ '^sha256:[0-9a-f]{64}$'),
  intake_state text,
  family_state text NOT NULL CHECK (family_state IN ('resolved', 'unresolved')),
  family_rule_key text,
  blocker_code text,
  recovery_instruction text,
  evidence_refs jsonb NOT NULL
    CHECK (
      jsonb_typeof(evidence_refs) = 'array'
      AND jsonb_array_length(evidence_refs) > 0
    ),
  revision_hash text NOT NULL
    CHECK (revision_hash ~ '^sha256:[0-9a-f]{64}$'),
  created_by text NOT NULL CHECK (length(btrim(created_by)) > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT makesafe_state_identity_case_shape CHECK (
    (authority_kind = 'effective_intake_case' AND effective_case_id IS NOT NULL)
    OR
    (authority_kind <> 'effective_intake_case' AND effective_case_id IS NULL)
  ),
  CONSTRAINT makesafe_state_identity_family_shape CHECK (
    (family_state = 'resolved' AND family_rule_key IS NOT NULL)
    OR
    (
      family_state = 'unresolved'
      AND family_rule_key IS NULL
      AND length(btrim(COALESCE(recovery_instruction, ''))) > 0
    )
  ),
  UNIQUE (job_id, revision_hash)
);

CREATE INDEX IF NOT EXISTS idx_makesafe_state_identity_revisions_current
  ON public.makesafe_state_identity_revisions
  (job_id, created_at DESC, id DESC);

CREATE OR REPLACE VIEW public.makesafe_state_identity_current_v2
WITH (security_invoker = true)
AS
SELECT DISTINCT ON (job_id)
  id,
  org_id,
  job_id,
  authority_kind,
  effective_case_id,
  source_instruction_id,
  source_version,
  source_content_hash,
  lineage_id,
  lineage_version,
  lineage_correction_hash,
  lineage_supersession_hash,
  intake_state,
  family_state,
  family_rule_key,
  blocker_code,
  recovery_instruction,
  evidence_refs,
  revision_hash,
  created_by,
  created_at
FROM public.makesafe_state_identity_revisions
ORDER BY job_id, created_at DESC, id DESC;

CREATE TABLE IF NOT EXISTS public.makesafe_state_seed_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_key text NOT NULL UNIQUE
    CHECK (length(btrim(run_key)) BETWEEN 1 AND 160),
  selection_hash text NOT NULL
    CHECK (selection_hash ~ '^sha256:[0-9a-f]{64}$'),
  requested_count integer NOT NULL CHECK (requested_count BETWEEN 1 AND 500),
  result_json jsonb NOT NULL CHECK (jsonb_typeof(result_json) = 'object'),
  applied_by text NOT NULL CHECK (length(btrim(applied_by)) > 0),
  applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.reject_makesafe_state_seed_audit_mutation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
END;
$$;

DROP TRIGGER IF EXISTS trg_makesafe_state_identity_revisions_append_only
  ON public.makesafe_state_identity_revisions;
CREATE TRIGGER trg_makesafe_state_identity_revisions_append_only
  BEFORE UPDATE OR DELETE ON public.makesafe_state_identity_revisions
  FOR EACH ROW EXECUTE FUNCTION public.reject_makesafe_state_seed_audit_mutation();

DROP TRIGGER IF EXISTS trg_makesafe_state_seed_runs_append_only
  ON public.makesafe_state_seed_runs;
CREATE TRIGGER trg_makesafe_state_seed_runs_append_only
  BEFORE UPDATE OR DELETE ON public.makesafe_state_seed_runs
  FOR EACH ROW EXECUTE FUNCTION public.reject_makesafe_state_seed_audit_mutation();

CREATE OR REPLACE FUNCTION public.makesafe_fact_hash_v1(
  p_kind text,
  p_payload jsonb
)
RETURNS text
LANGUAGE sql
IMMUTABLE
STRICT
SET search_path = public, extensions
AS $$
  SELECT 'sha256:' || encode(
    extensions.digest(
      convert_to(
        'SecureWorks:make-safe-fact:v1:' || p_kind || E'\n' ||
          public.makesafe_canonical_json_v1(p_payload),
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  );
$$;

CREATE OR REPLACE FUNCTION public.stamp_makesafe_fact_identity_v1()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  v_is_makesafe boolean;
  v_payload jsonb;
  v_hash text;
  v_old_hash text;
  v_old_version bigint;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM public.jobs j
    WHERE j.id = NEW.job_id AND j.type = 'makesafe'
  ) INTO v_is_makesafe;
  IF NOT v_is_makesafe THEN
    RETURN NEW;
  END IF;

  -- Hash the row that actually exists in this database instead of naming a
  -- brittle table-specific column list. Identity fields and trigger-maintained
  -- timestamps are excluded so a no-op write keeps the same fact identity.
  v_payload := to_jsonb(NEW)
    - 'makesafe_fact_version'
    - 'makesafe_content_hash'
    - 'updated_at';

  v_hash := public.makesafe_fact_hash_v1(TG_TABLE_NAME, v_payload);
  IF TG_OP = 'INSERT' THEN
    NEW.makesafe_fact_version := 1;
    NEW.makesafe_content_hash := v_hash;
    RETURN NEW;
  END IF;

  v_old_hash := OLD.makesafe_content_hash;
  v_old_version := OLD.makesafe_fact_version;
  IF v_old_hash IS NULL OR v_old_version IS NULL THEN
    NEW.makesafe_fact_version := 1;
    NEW.makesafe_content_hash := v_hash;
  ELSIF v_hash IS DISTINCT FROM v_old_hash THEN
    NEW.makesafe_fact_version := v_old_version + 1;
    NEW.makesafe_content_hash := v_hash;
  ELSE
    NEW.makesafe_fact_version := v_old_version;
    NEW.makesafe_content_hash := v_old_hash;
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.stamp_makesafe_intake_case_identity_v1()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  v_source_payload jsonb;
  v_source_hash text;
  v_correction_hash text;
  v_supersession_hash text;
BEGIN
  -- The case row is the mutable source fact. Tracking columns and timestamps
  -- are excluded so a no-op maintenance write keeps the same source identity.
  v_source_payload := to_jsonb(NEW)
    - 'source_version'
    - 'source_content_hash'
    - 'lineage_version'
    - 'lineage_correction_hash'
    - 'lineage_supersession_hash'
    - 'updated_at'
    - 'observed_at'
    - 'last_decision_at';
  v_source_hash := public.makesafe_fact_hash_v1(
    'intake-source',
    v_source_payload
  );
  v_correction_hash := public.makesafe_fact_hash_v1(
    'lineage-corrections',
    jsonb_build_object(
      'case_id', NEW.id,
      'case_corrections', COALESCE((
        SELECT jsonb_agg(to_jsonb(x) ORDER BY x.created_at, x.id)
        FROM public.makesafe_intake_case_authority_corrections x
        WHERE x.legacy_case_id = NEW.id OR x.effective_case_id = NEW.id
      ), '[]'::jsonb),
      'source_corrections', COALESCE((
        SELECT jsonb_agg(to_jsonb(x) ORDER BY x.created_at, x.id)
        FROM public.makesafe_intake_source_authority_corrections x
        WHERE x.legacy_case_id = NEW.id OR x.effective_case_id = NEW.id
      ), '[]'::jsonb)
    )
  );
  v_supersession_hash := public.makesafe_fact_hash_v1(
    'lineage-supersessions',
    jsonb_build_object(
      'case_id', NEW.id,
      'supersessions', COALESCE((
        SELECT jsonb_agg(to_jsonb(x) ORDER BY x.created_at, x.id)
        FROM
          public.makesafe_intake_source_authority_correction_supersessions x
        WHERE x.prior_authority_case_id = NEW.id
           OR x.effective_case_id = NEW.id
      ), '[]'::jsonb)
    )
  );

  IF TG_OP = 'INSERT' THEN
    NEW.source_version := 1;
    NEW.lineage_version := 1;
  ELSE
    NEW.source_version := CASE
      WHEN OLD.source_version IS NULL OR OLD.source_content_hash IS NULL THEN 1
      WHEN OLD.source_content_hash IS DISTINCT FROM v_source_hash
        THEN OLD.source_version + 1
      ELSE OLD.source_version
    END;
    NEW.lineage_version := CASE
      WHEN OLD.lineage_version IS NULL
        OR OLD.lineage_correction_hash IS NULL
        OR OLD.lineage_supersession_hash IS NULL THEN 1
      WHEN OLD.lineage_correction_hash IS DISTINCT FROM v_correction_hash
        OR OLD.lineage_supersession_hash IS DISTINCT FROM v_supersession_hash
        THEN OLD.lineage_version + 1
      ELSE OLD.lineage_version
    END;
  END IF;
  NEW.source_content_hash := v_source_hash;
  NEW.lineage_correction_hash := v_correction_hash;
  NEW.lineage_supersession_hash := v_supersession_hash;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_makesafe_intake_cases_stamp_state_v2
  ON public.makesafe_intake_cases;
CREATE TRIGGER trg_makesafe_intake_cases_stamp_state_v2
  BEFORE INSERT OR UPDATE ON public.makesafe_intake_cases
  FOR EACH ROW
  EXECUTE FUNCTION public.stamp_makesafe_intake_case_identity_v1();

CREATE OR REPLACE FUNCTION public.refresh_makesafe_case_lineage_identity_v1()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_TABLE_NAME = 'makesafe_intake_case_authority_corrections' THEN
    UPDATE public.makesafe_intake_cases
    SET lineage_version = lineage_version
    WHERE id IN (NEW.legacy_case_id, NEW.effective_case_id);
  ELSIF TG_TABLE_NAME = 'makesafe_intake_source_authority_corrections' THEN
    UPDATE public.makesafe_intake_cases
    SET lineage_version = lineage_version
    WHERE id IN (NEW.legacy_case_id, NEW.effective_case_id);
  ELSE
    UPDATE public.makesafe_intake_cases
    SET lineage_version = lineage_version
    WHERE id IN (NEW.prior_authority_case_id, NEW.effective_case_id);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_makesafe_case_authority_corrections_state_v2
  ON public.makesafe_intake_case_authority_corrections;
CREATE TRIGGER trg_makesafe_case_authority_corrections_state_v2
  AFTER INSERT ON public.makesafe_intake_case_authority_corrections
  FOR EACH ROW
  EXECUTE FUNCTION public.refresh_makesafe_case_lineage_identity_v1();

DROP TRIGGER IF EXISTS trg_makesafe_source_authority_corrections_state_v2
  ON public.makesafe_intake_source_authority_corrections;
CREATE TRIGGER trg_makesafe_source_authority_corrections_state_v2
  AFTER INSERT ON public.makesafe_intake_source_authority_corrections
  FOR EACH ROW
  EXECUTE FUNCTION public.refresh_makesafe_case_lineage_identity_v1();

DROP TRIGGER IF EXISTS trg_makesafe_source_authority_supersessions_state_v2
  ON public.makesafe_intake_source_authority_correction_supersessions;
CREATE TRIGGER trg_makesafe_source_authority_supersessions_state_v2
  AFTER INSERT
  ON public.makesafe_intake_source_authority_correction_supersessions
  FOR EACH ROW
  EXECUTE FUNCTION public.refresh_makesafe_case_lineage_identity_v1();

DO $$
DECLARE
  relation_name text;
BEGIN
  FOREACH relation_name IN ARRAY ARRAY[
    'makesafe_attendance_cycles',
    'job_assignments',
    'job_service_reports',
    'job_documents',
    'job_media',
    'makesafe_report_packs'
  ]
  LOOP
    EXECUTE format(
      'DROP TRIGGER IF EXISTS %I ON public.%I',
      'trg_' || relation_name || '_fact_identity_v1',
      relation_name
    );
    EXECUTE format(
      'CREATE TRIGGER %I BEFORE INSERT OR UPDATE ON public.%I
       FOR EACH ROW EXECUTE FUNCTION public.stamp_makesafe_fact_identity_v1()',
      'trg_' || relation_name || '_fact_identity_v1',
      relation_name
    );
  END LOOP;
END;
$$;

ALTER TABLE public.makesafe_cancellation_decisions
  ADD COLUMN IF NOT EXISTS evidence_refs jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE public.makesafe_cancellation_decisions
  DROP CONSTRAINT IF EXISTS makesafe_cancellation_evidence_refs_check;
ALTER TABLE public.makesafe_cancellation_decisions
  ADD CONSTRAINT makesafe_cancellation_evidence_refs_check CHECK (
    jsonb_typeof(evidence_refs) = 'array'
  ) NOT VALID;

CREATE OR REPLACE FUNCTION public.seed_makesafe_state_authority_v1(
  p_run_key text,
  p_applied_by text,
  p_selection_hash text,
  p_job_ids uuid[]
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, extensions
AS $$
DECLARE
  v_requested integer;
  v_matched integer;
  v_identity_count integer;
  v_cycle_count integer;
  v_fact_count integer := 0;
  v_terminal_count integer;
  v_cancellation_count integer;
  v_family_resolved integer;
  v_family_unresolved integer;
  v_result jsonb;
  v_existing public.makesafe_state_seed_runs%ROWTYPE;
BEGIN
  IF length(btrim(COALESCE(p_run_key, ''))) = 0
     OR length(btrim(COALESCE(p_applied_by, ''))) = 0
     OR COALESCE(p_selection_hash, '') !~ '^sha256:[0-9a-f]{64}$' THEN
    RAISE EXCEPTION
      'run key, attribution, and sha256 selection hash are required';
  END IF;
  v_requested := cardinality(p_job_ids);
  IF v_requested < 1 OR v_requested > 500 THEN
    RAISE EXCEPTION 'p_job_ids must contain between 1 and 500 jobs';
  END IF;
  IF v_requested <> (
    SELECT count(DISTINCT id) FROM unnest(p_job_ids) ids(id)
  ) THEN
    RAISE EXCEPTION 'p_job_ids contains duplicate jobs';
  END IF;

  SELECT * INTO v_existing
  FROM public.makesafe_state_seed_runs
  WHERE run_key = p_run_key;
  IF FOUND THEN
    IF v_existing.selection_hash IS DISTINCT FROM p_selection_hash THEN
      RAISE EXCEPTION 'seed run key already belongs to a different selection';
    END IF;
    RETURN v_existing.result_json ||
      jsonb_build_object('idempotent_replay', true);
  END IF;

  SELECT count(*) INTO v_matched
  FROM public.jobs j
  WHERE j.id = ANY(p_job_ids)
    AND j.type = 'makesafe';
  IF v_matched <> v_requested THEN
    RAISE EXCEPTION 'seed selection contains a missing or non-make-safe job';
  END IF;

  -- Publish the five family shapes sealed by U4. Job binding below still fails
  -- closed when the stored evidence cannot distinguish a family or builder
  -- applicability; publishing a rule is not permission to guess a binding.
  WITH seeds AS (
    SELECT *
    FROM (VALUES
      (
        'physical_makesafe'::text,
        'physical'::text,
        'ses-builder-family-matrix/2026-07-27.1:physical_makesafe',
        5::integer,
        ARRAY[]::text[],
        ARRAY[]::text[]
      ),
      (
        'temporary_fencing',
        'physical',
        'ses-builder-family-matrix/2026-07-27.1:temporary_fencing',
        5,
        ARRAY[]::text[],
        ARRAY[]::text[]
      ),
      (
        'ordinary_roof_portal',
        'portal',
        'ses-builder-family-matrix/2026-07-27.1:ordinary_roof_portal',
        0,
        ARRAY[]::text[],
        ARRAY['roof_report']::text[]
      ),
      (
        'own_template_roof',
        'report_only',
        'ses-builder-family-matrix/2026-07-27.1:own_template_roof',
        0,
        ARRAY['roof_report']::text[],
        ARRAY[]::text[]
      ),
      (
        'assessment_quote',
        'portal',
        'ses-builder-family-matrix/2026-07-27.1:assessment_quote',
        0,
        ARRAY[]::text[],
        ARRAY['assessment', 'photos', 'scope']::text[]
      )
    ) AS s(
      family_code,
      family_kind,
      matrix_revision,
      completion_photo_floor,
      required_document_types,
      required_portal_roles
    )
  ),
  inserted AS (
    INSERT INTO public.makesafe_family_rule_revisions (
      family_code,
      family_kind,
      matrix_revision,
      matrix_content_hash,
      completion_photo_floor,
      required_document_types,
      required_portal_roles,
      created_by
    )
    SELECT
      s.family_code,
      s.family_kind,
      s.matrix_revision,
      public.makesafe_fact_hash_v1(
        'family-rule',
        jsonb_build_object(
          'family_code', s.family_code,
          'family_kind', s.family_kind,
          'matrix_revision', s.matrix_revision,
          'completion_photo_floor', s.completion_photo_floor,
          'required_document_types', to_jsonb(s.required_document_types),
          'required_portal_roles', to_jsonb(s.required_portal_roles)
        )
      ),
      s.completion_photo_floor,
      s.required_document_types,
      s.required_portal_roles,
      p_applied_by
    FROM seeds s
    ON CONFLICT (family_code, matrix_revision) DO NOTHING
    RETURNING id
  )
  SELECT count(*) INTO v_fact_count FROM inserted;

  INSERT INTO public.makesafe_family_rule_current (
    family_code, revision_id, updated_by
  )
  SELECT r.family_code, r.id, p_applied_by
  FROM public.makesafe_family_rule_revisions r
  WHERE r.matrix_revision IN (
    'ses-builder-family-matrix/2026-07-27.1:physical_makesafe',
    'ses-builder-family-matrix/2026-07-27.1:temporary_fencing',
    'ses-builder-family-matrix/2026-07-27.1:ordinary_roof_portal',
    'ses-builder-family-matrix/2026-07-27.1:own_template_roof',
    'ses-builder-family-matrix/2026-07-27.1:assessment_quote'
  )
  ON CONFLICT (family_code) DO UPDATE
  SET revision_id = EXCLUDED.revision_id,
      updated_at = transaction_timestamp(),
      updated_by = EXCLUDED.updated_by
  WHERE makesafe_family_rule_current.revision_id IS DISTINCT FROM
    EXCLUDED.revision_id;

  WITH inserted AS (
    INSERT INTO public.makesafe_attendance_cycles (
      job_id, cycle_number, opened_at, open_reason
    )
    SELECT
      j.id,
      GREATEST(COALESCE(d.cycle_number, 1), 1),
      COALESCE(d.created_at, j.created_at, transaction_timestamp()),
      'state_authority_seed_existing_job'
    FROM public.jobs j
    LEFT JOIN public.makesafe_job_details d ON d.job_id = j.id
    WHERE j.id = ANY(p_job_ids)
      AND NOT EXISTS (
        SELECT 1 FROM public.makesafe_attendance_cycles c
        WHERE c.job_id = j.id
      )
    ON CONFLICT (job_id, cycle_number) DO NOTHING
    RETURNING id
  )
  SELECT count(*) INTO v_cycle_count FROM inserted;

  WITH single_cycle AS (
    SELECT job_id, (array_agg(id ORDER BY id))[1] AS cycle_id
    FROM public.makesafe_attendance_cycles
    WHERE job_id = ANY(p_job_ids)
    GROUP BY job_id
    HAVING count(*) = 1
  )
  UPDATE public.makesafe_job_details d
  SET attendance_cycle_id = s.cycle_id,
      cycle_attribution = 'bound',
      updated_at = transaction_timestamp()
  FROM single_cycle s
  WHERE d.job_id = s.job_id
    AND (
      d.attendance_cycle_id IS DISTINCT FROM s.cycle_id
      OR d.cycle_attribution IS DISTINCT FROM 'bound'
    );

  WITH single_cycle AS (
    SELECT job_id, (array_agg(id ORDER BY id))[1] AS cycle_id
    FROM public.makesafe_attendance_cycles
    WHERE job_id = ANY(p_job_ids)
    GROUP BY job_id
    HAVING count(*) = 1
  ),
  updated AS (
    UPDATE public.job_assignments f
    SET attendance_cycle_id = s.cycle_id,
        cycle_attribution = 'bound'
    FROM single_cycle s
    WHERE f.job_id = s.job_id
      AND (
        f.attendance_cycle_id IS DISTINCT FROM s.cycle_id
        OR f.cycle_attribution IS DISTINCT FROM 'bound'
      )
    RETURNING f.id
  )
  SELECT v_fact_count + count(*) INTO v_fact_count FROM updated;

  WITH exact_cycle AS (
    SELECT r.id AS report_id, c.id AS cycle_id
    FROM public.job_service_reports r
    JOIN public.makesafe_attendance_cycles c
      ON c.job_id = r.job_id
     AND c.cycle_number = COALESCE(r.cycle_number, 1)
    WHERE r.job_id = ANY(p_job_ids)
  ),
  updated AS (
    UPDATE public.job_service_reports f
    SET attendance_cycle_id = e.cycle_id,
        cycle_attribution = 'bound'
    FROM exact_cycle e
    WHERE f.id = e.report_id
      AND (
        f.attendance_cycle_id IS DISTINCT FROM e.cycle_id
        OR f.cycle_attribution IS DISTINCT FROM 'bound'
      )
    RETURNING f.id
  )
  SELECT v_fact_count + count(*) INTO v_fact_count FROM updated;

  WITH single_cycle AS (
    SELECT job_id, (array_agg(id ORDER BY id))[1] AS cycle_id
    FROM public.makesafe_attendance_cycles
    WHERE job_id = ANY(p_job_ids)
    GROUP BY job_id
    HAVING count(*) = 1
  ),
  updated_docs AS (
    UPDATE public.job_documents f
    SET attendance_cycle_id = s.cycle_id,
        cycle_attribution = 'bound'
    FROM single_cycle s
    WHERE f.job_id = s.job_id
      AND (
        f.attendance_cycle_id IS DISTINCT FROM s.cycle_id
        OR f.cycle_attribution IS DISTINCT FROM 'bound'
      )
    RETURNING f.id
  )
  SELECT v_fact_count + count(*) INTO v_fact_count FROM updated_docs;

  WITH single_cycle AS (
    SELECT job_id, (array_agg(id ORDER BY id))[1] AS cycle_id
    FROM public.makesafe_attendance_cycles
    WHERE job_id = ANY(p_job_ids)
    GROUP BY job_id
    HAVING count(*) = 1
  ),
  updated_media AS (
    UPDATE public.job_media f
    SET attendance_cycle_id = s.cycle_id,
        cycle_attribution = 'bound'
    FROM single_cycle s
    WHERE f.job_id = s.job_id
      AND (
        f.attendance_cycle_id IS DISTINCT FROM s.cycle_id
        OR f.cycle_attribution IS DISTINCT FROM 'bound'
      )
    RETURNING f.id
  )
  SELECT v_fact_count + count(*) INTO v_fact_count FROM updated_media;

  WITH inserted AS (
    INSERT INTO public.makesafe_report_pack_cycles (
      pack_id, job_id, attendance_cycle_id, cycle_attribution
    )
    SELECT p.id, p.job_id, s.cycle_id, 'bound'
    FROM public.makesafe_report_packs p
    JOIN (
      SELECT job_id, (array_agg(id ORDER BY id))[1] AS cycle_id
      FROM public.makesafe_attendance_cycles
      WHERE job_id = ANY(p_job_ids)
      GROUP BY job_id
      HAVING count(*) = 1
    ) s ON s.job_id = p.job_id
    WHERE NOT EXISTS (
      SELECT 1 FROM public.makesafe_report_pack_cycles pc
      WHERE pc.pack_id = p.id
    )
    ON CONFLICT (pack_id, attendance_cycle_id) DO NOTHING
    RETURNING id
  )
  SELECT v_fact_count + count(*) INTO v_fact_count FROM inserted;

  -- Touch every selected fact once. The BEFORE triggers compute the canonical
  -- hash and v1 version; no-op future writes preserve both.
  UPDATE public.makesafe_attendance_cycles
  SET makesafe_fact_version = makesafe_fact_version
  WHERE job_id = ANY(p_job_ids)
    AND (makesafe_fact_version IS NULL OR makesafe_content_hash IS NULL);
  GET DIAGNOSTICS v_matched = ROW_COUNT;
  v_fact_count := v_fact_count + v_matched;

  UPDATE public.job_assignments
  SET makesafe_fact_version = makesafe_fact_version
  WHERE job_id = ANY(p_job_ids)
    AND (makesafe_fact_version IS NULL OR makesafe_content_hash IS NULL);
  GET DIAGNOSTICS v_matched = ROW_COUNT;
  v_fact_count := v_fact_count + v_matched;

  UPDATE public.job_service_reports
  SET makesafe_fact_version = makesafe_fact_version
  WHERE job_id = ANY(p_job_ids)
    AND (makesafe_fact_version IS NULL OR makesafe_content_hash IS NULL);
  GET DIAGNOSTICS v_matched = ROW_COUNT;
  v_fact_count := v_fact_count + v_matched;

  UPDATE public.job_documents
  SET makesafe_fact_version = makesafe_fact_version
  WHERE job_id = ANY(p_job_ids)
    AND (makesafe_fact_version IS NULL OR makesafe_content_hash IS NULL);
  GET DIAGNOSTICS v_matched = ROW_COUNT;
  v_fact_count := v_fact_count + v_matched;

  UPDATE public.job_media
  SET makesafe_fact_version = makesafe_fact_version
  WHERE job_id = ANY(p_job_ids)
    AND (makesafe_fact_version IS NULL OR makesafe_content_hash IS NULL);
  GET DIAGNOSTICS v_matched = ROW_COUNT;
  v_fact_count := v_fact_count + v_matched;

  UPDATE public.makesafe_report_packs
  SET makesafe_fact_version = makesafe_fact_version
  WHERE job_id = ANY(p_job_ids)
    AND (makesafe_fact_version IS NULL OR makesafe_content_hash IS NULL);
  GET DIAGNOSTICS v_matched = ROW_COUNT;
  v_fact_count := v_fact_count + v_matched;

  WITH selected_cases AS (
    SELECT
      c.*,
      count(*) OVER (
        PARTITION BY COALESCE(c.target_job_id, c.job_id)
      ) AS case_count
    FROM public.makesafe_intake_cases c
    WHERE (
        c.job_id = ANY(p_job_ids)
        OR c.target_job_id = ANY(p_job_ids)
      )
      AND c.state IN ('confirmed_live_job', 'blocked_live_job')
  )
  UPDATE public.makesafe_intake_cases c
  SET source_version = COALESCE(c.source_version, 1),
      source_content_hash = COALESCE(
        c.source_content_hash,
        public.makesafe_fact_hash_v1(
          'intake-source',
          jsonb_build_object(
            'case_id', c.id,
            'instruction_key', c.instruction_key,
            'source_fingerprint', c.source_fingerprint,
            'raw_identity_json', c.raw_identity_json,
            'received_at', c.received_at
          )
        )
      ),
      lineage_version = COALESCE(c.lineage_version, 1),
      lineage_correction_hash = COALESCE(
        c.lineage_correction_hash,
        public.makesafe_fact_hash_v1(
          'lineage-corrections',
          jsonb_build_object(
            'case_id', c.id,
            'case_corrections', COALESCE((
              SELECT jsonb_agg(to_jsonb(x) ORDER BY x.created_at, x.id)
              FROM public.makesafe_intake_case_authority_corrections x
              WHERE x.legacy_case_id = c.id OR x.effective_case_id = c.id
            ), '[]'::jsonb),
            'source_corrections', COALESCE((
              SELECT jsonb_agg(to_jsonb(x) ORDER BY x.created_at, x.id)
              FROM public.makesafe_intake_source_authority_corrections x
              WHERE x.legacy_case_id = c.id OR x.effective_case_id = c.id
            ), '[]'::jsonb)
          )
        )
      ),
      lineage_supersession_hash = COALESCE(
        c.lineage_supersession_hash,
        public.makesafe_fact_hash_v1(
          'lineage-supersessions',
          jsonb_build_object(
            'case_id', c.id,
            'supersessions', COALESCE((
              SELECT jsonb_agg(to_jsonb(x) ORDER BY x.created_at, x.id)
              FROM
                public.makesafe_intake_source_authority_correction_supersessions
                  x
              WHERE x.prior_authority_case_id = c.id
                 OR x.effective_case_id = c.id
            ), '[]'::jsonb)
          )
        )
      )
  FROM selected_cases s
  WHERE c.id = s.id;

  WITH job_inputs AS (
    SELECT
      j.*,
      d.external_ref AS detail_external_ref,
      d.report_type,
      lower(COALESCE(d.requesting_company_slug, '')) AS company_slug,
      lower(concat_ws(
        ' ',
        d.requesting_company_slug,
        d.requesting_company_name,
        d.external_ref,
        j.metadata->'requesting_company'->>'slug',
        j.metadata->'requesting_company'->>'name'
      )) AS builder_token,
      lower(COALESCE(
        j.metadata->>'ses_family',
        j.metadata->>'makesafe_job_family',
        j.metadata->>'makesafe_family',
        j.metadata->>'job_family',
        d.report_type,
        ''
      )) AS family_token
    FROM public.jobs j
    LEFT JOIN public.makesafe_job_details d ON d.job_id = j.id
    WHERE j.id = ANY(p_job_ids)
  ),
  job_context AS (
    SELECT
      i.*,
      CASE
        WHEN (
          i.builder_token ~ '(^|[^a-z0-9])(aj|ajs|ajbr)([^a-z0-9]|$)'
          OR i.builder_token LIKE '%alliance joinery%'
        )
          AND i.family_token NOT LIKE '%temp%fenc%'
          THEN 'physical_makesafe'
        WHEN i.family_token LIKE '%temp%fenc%'
          THEN 'temporary_fencing'
        WHEN i.family_token LIKE '%assessment%'
          OR i.family_token LIKE '%report_and_quote%'
          THEN 'assessment_quote'
        WHEN i.family_token LIKE '%roof%'
          AND (
            i.metadata->>'own_template_requested' = 'true'
            OR lower(COALESCE(i.metadata->>'report_delivery', '')) =
              'own_document'
            OR i.family_token LIKE '%own%template%'
            OR i.family_token LIKE '%strata%'
          )
          THEN 'own_template_roof'
        WHEN i.family_token LIKE '%roof%'
          AND (
            i.builder_token ~ '(^|[^a-z0-9])mlb([^a-z0-9]|$)'
            OR i.builder_token LIKE '%ml builders%'
            OR i.builder_token LIKE '%major loss builders%'
            OR i.builder_token LIKE '%mlbuilders%'
          )
          THEN 'ordinary_roof_portal'
        WHEN i.family_token IN (
          'general_makesafe',
          'physical_makesafe',
          'makesafe'
        )
          THEN 'physical_makesafe'
        ELSE NULL
      END AS family_code
    FROM job_inputs i
  ),
  case_candidates AS (
    SELECT
      j.id AS job_id,
      c.id AS case_id
    FROM job_context j
    JOIN public.makesafe_intake_cases c
      ON c.job_id = j.id OR c.target_job_id = j.id
    WHERE c.state IN ('confirmed_live_job', 'blocked_live_job')
  ),
  case_counts AS (
    SELECT
      j.id AS job_id,
      count(c.id) AS case_count,
      (array_agg(c.id ORDER BY c.id))[1] AS case_id
    FROM job_context j
    LEFT JOIN case_candidates c ON c.job_id = j.id
    GROUP BY j.id
  ),
  source_rows AS (
    SELECT
      j.org_id,
      j.id AS job_id,
      CASE
        WHEN cc.case_count = 1 THEN 'effective_intake_case'
        WHEN cc.case_count = 0 THEN 'legacy_job_record'
        ELSE 'unresolved_authority'
      END AS authority_kind,
      CASE WHEN cc.case_count = 1 THEN c.id ELSE NULL END AS effective_case_id,
      CASE
        WHEN cc.case_count = 1 THEN c.instruction_key
        WHEN cc.case_count = 0 THEN 'legacy-job:' || j.id::text
        ELSE 'unresolved-job:' || j.id::text
      END AS source_instruction_id,
      COALESCE(c.source_version, 1) AS source_version,
      COALESCE(
        c.source_content_hash,
        public.makesafe_fact_hash_v1(
          'legacy-job-source',
          jsonb_build_object(
            'job_id', j.id,
            'job_number', j.job_number,
            'external_ref', j.detail_external_ref,
            'created_at', j.created_at
          )
        )
      ) AS source_content_hash,
      COALESCE(c.lineage_id::text, j.id::text) AS lineage_id,
      COALESCE(c.lineage_version, 1) AS lineage_version,
      COALESCE(
        c.lineage_correction_hash,
        public.makesafe_fact_hash_v1(
          'legacy-lineage-corrections',
          jsonb_build_object('job_id', j.id, 'corrections', '[]'::jsonb)
        )
      ) AS lineage_correction_hash,
      COALESCE(
        c.lineage_supersession_hash,
        public.makesafe_fact_hash_v1(
          'legacy-lineage-supersessions',
          jsonb_build_object('job_id', j.id, 'supersessions', '[]'::jsonb)
        )
      ) AS lineage_supersession_hash,
      CASE
        WHEN cc.case_count > 1 THEN 'blocked_live_job'
        ELSE c.state
      END AS intake_state,
      CASE
        WHEN j.family_code IS NOT NULL THEN 'resolved'
        ELSE 'unresolved'
      END AS family_state,
      j.family_code AS family_rule_key,
      CASE
        WHEN cc.case_count > 1 THEN 'multiple_effective_authorities'
        WHEN j.family_token LIKE '%roof%'
          THEN 'builder_family_applicability_unresolved'
        WHEN j.family_code IS NULL THEN 'family_unclassified'
        ELSE NULL
      END AS blocker_code,
      CASE
        WHEN cc.case_count > 1
          THEN 'Choose the one source instruction that owns this job.'
        WHEN j.family_token LIKE '%roof%'
          THEN 'Confirm the builder and whether this roof report is a portal handoff or our own document.'
        WHEN j.family_code IS NULL
          THEN 'Classify the job family from its original work-order evidence.'
        ELSE NULL
      END AS recovery_instruction,
      jsonb_build_array(
        'jobs:' || j.id::text,
        CASE
          WHEN c.id IS NOT NULL
            THEN 'makesafe_intake_cases:' || c.id::text
          ELSE 'makesafe_job_details:' || j.id::text
        END
      ) AS evidence_refs
    FROM job_context j
    JOIN case_counts cc ON cc.job_id = j.id
    LEFT JOIN public.makesafe_intake_cases c ON c.id = cc.case_id
  ),
  revision_rows AS (
    SELECT
      s.*,
      public.makesafe_fact_hash_v1(
        'state-identity-revision',
        jsonb_build_object(
          'job_id', s.job_id,
          'authority_kind', s.authority_kind,
          'effective_case_id', s.effective_case_id,
          'source_instruction_id', s.source_instruction_id,
          'source_version', s.source_version,
          'source_content_hash', s.source_content_hash,
          'lineage_id', s.lineage_id,
          'lineage_version', s.lineage_version,
          'lineage_correction_hash', s.lineage_correction_hash,
          'lineage_supersession_hash', s.lineage_supersession_hash,
          'intake_state', s.intake_state,
          'family_state', s.family_state,
          'family_rule_key', s.family_rule_key,
          'blocker_code', s.blocker_code,
          'evidence_refs', s.evidence_refs
        )
      ) AS revision_hash
    FROM source_rows s
  ),
  inserted AS (
    INSERT INTO public.makesafe_state_identity_revisions (
      org_id,
      job_id,
      authority_kind,
      effective_case_id,
      source_instruction_id,
      source_version,
      source_content_hash,
      lineage_id,
      lineage_version,
      lineage_correction_hash,
      lineage_supersession_hash,
      intake_state,
      family_state,
      family_rule_key,
      blocker_code,
      recovery_instruction,
      evidence_refs,
      revision_hash,
      created_by
    )
    SELECT
      r.org_id,
      r.job_id,
      r.authority_kind,
      r.effective_case_id,
      r.source_instruction_id,
      r.source_version,
      r.source_content_hash,
      r.lineage_id,
      r.lineage_version,
      r.lineage_correction_hash,
      r.lineage_supersession_hash,
      r.intake_state,
      r.family_state,
      r.family_rule_key,
      r.blocker_code,
      r.recovery_instruction,
      r.evidence_refs,
      r.revision_hash,
      p_applied_by
    FROM revision_rows r
    ON CONFLICT (job_id, revision_hash) DO NOTHING
    RETURNING id
  )
  SELECT count(*) INTO v_identity_count FROM inserted;

  WITH cycle_sets AS (
    SELECT
      j.id AS job_id,
      j.org_id,
      array_agg(c.id ORDER BY c.id) AS cycle_ids,
      public.makesafe_attendance_cycle_set_hash_v1(
        array_agg(c.id ORDER BY c.id)
      ) AS cycle_set_hash
    FROM public.jobs j
    JOIN public.makesafe_attendance_cycles c ON c.job_id = j.id
    WHERE j.id = ANY(p_job_ids)
    GROUP BY j.id, j.org_id
  ),
  closeout AS (
    SELECT DISTINCT ON (p.job_id)
      p.job_id,
      p.id AS pack_id,
      COALESCE(
        NULLIF(upper(p.invoice_status), ''),
        upper(x.status)
      ) AS invoice_status,
      p.xero_invoice_id,
      x.id AS invoice_id,
      p.sent_at
    FROM public.makesafe_report_packs p
    LEFT JOIN public.xero_invoices x
      ON x.job_id = p.job_id
     AND x.invoice_type = 'ACCREC'
     AND upper(x.status) IN ('AUTHORISED', 'PAID')
    WHERE p.job_id = ANY(p_job_ids)
      AND COALESCE(p.pack_kind, 'main') = 'main'
      AND lower(COALESCE(p.status, '')) IN (
        'sent', 'sent_marker_failed', 'sent_not_closed', 'close_failed'
      )
      AND COALESCE(NULLIF(upper(p.invoice_status), ''), upper(x.status))
        IN ('AUTHORISED', 'PAID')
    ORDER BY p.job_id, p.sent_at DESC NULLS LAST, p.id DESC
  ),
  inserted AS (
    INSERT INTO public.makesafe_terminal_proofs (
      org_id,
      job_id,
      kind,
      attendance_cycle_ids,
      attendance_cycle_set_hash,
      evidence_refs,
      proven_by,
      proven_at
    )
    SELECT
      cs.org_id,
      cs.job_id,
      'verified_historical_closeout',
      cs.cycle_ids,
      cs.cycle_set_hash,
      to_jsonb(array_remove(ARRAY[
        'makesafe_report_packs:' || co.pack_id::text,
        CASE WHEN co.invoice_id IS NOT NULL
          THEN 'xero_invoices:' || co.invoice_id::text END,
        CASE WHEN co.xero_invoice_id IS NOT NULL
          THEN 'xero_invoice_id:' || co.xero_invoice_id END
      ]::text[], NULL)),
      p_applied_by,
      COALESCE(co.sent_at, transaction_timestamp())
    FROM cycle_sets cs
    JOIN closeout co ON co.job_id = cs.job_id
    WHERE NOT EXISTS (
      SELECT 1
      FROM public.makesafe_terminal_proofs p
      WHERE p.job_id = cs.job_id
        AND p.kind = 'verified_historical_closeout'
        AND p.attendance_cycle_set_hash = cs.cycle_set_hash
    )
    RETURNING id
  )
  SELECT count(*) INTO v_terminal_count FROM inserted;

  WITH cycle_sets AS (
    SELECT
      j.id AS job_id,
      j.org_id,
      array_agg(c.id ORDER BY c.id) AS cycle_ids,
      public.makesafe_attendance_cycle_set_hash_v1(
        array_agg(c.id ORDER BY c.id)
      ) AS cycle_set_hash
    FROM public.jobs j
    JOIN public.makesafe_attendance_cycles c ON c.job_id = j.id
    WHERE j.id = ANY(p_job_ids)
    GROUP BY j.id, j.org_id
  ),
  inserted AS (
    INSERT INTO public.makesafe_cancellation_decisions (
      org_id,
      job_id,
      attendance_cycle_set_hash,
      state,
      reason_code,
      note,
      decided_by,
      decided_at,
      evidence_refs
    )
    SELECT
      cs.org_id,
      cs.job_id,
      cs.cycle_set_hash,
      'confirmed',
      d.cancel_reason,
      d.cancel_note,
      COALESCE(NULLIF(d.cancelled_by, ''), p_applied_by),
      COALESCE(d.cancelled_at, j.updated_at, transaction_timestamp()),
      jsonb_build_array(
        'jobs:' || j.id::text,
        'makesafe_job_details:' || d.job_id::text
      )
    FROM cycle_sets cs
    JOIN public.jobs j ON j.id = cs.job_id
    JOIN public.makesafe_job_details d ON d.job_id = cs.job_id
    WHERE lower(j.status) IN ('cancelled', 'canceled')
      AND length(btrim(COALESCE(d.cancel_reason, ''))) > 0
      AND d.cancelled_at IS NOT NULL
      AND NOT EXISTS (
        SELECT 1
        FROM public.makesafe_cancellation_decisions existing
        WHERE existing.job_id = cs.job_id
          AND existing.state = 'confirmed'
          AND existing.attendance_cycle_set_hash = cs.cycle_set_hash
      )
    RETURNING id
  )
  SELECT count(*) INTO v_cancellation_count FROM inserted;

  SELECT
    count(*) FILTER (WHERE family_state = 'resolved'),
    count(*) FILTER (WHERE family_state = 'unresolved')
  INTO v_family_resolved, v_family_unresolved
  FROM public.makesafe_state_identity_current_v2
  WHERE job_id = ANY(p_job_ids);

  v_result := jsonb_build_object(
    'ok', true,
    'run_key', p_run_key,
    'selection_hash', p_selection_hash,
    'requested', v_requested,
    'identity_revisions_inserted', v_identity_count,
    'attendance_cycles_created', v_cycle_count,
    'facts_seeded_or_bound', v_fact_count,
    'family_resolved', v_family_resolved,
    'family_unresolved', v_family_unresolved,
    'terminal_proofs_inserted', v_terminal_count,
    'cancellations_inserted', v_cancellation_count,
    'idempotent_replay', false
  );

  INSERT INTO public.makesafe_state_seed_runs (
    run_key,
    selection_hash,
    requested_count,
    result_json,
    applied_by
  ) VALUES (
    p_run_key,
    p_selection_hash,
    v_requested,
    v_result,
    p_applied_by
  );

  RETURN v_result;
END;
$$;

CREATE TABLE IF NOT EXISTS public.makesafe_board_attention_marks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_key text NOT NULL CHECK (length(btrim(run_key)) BETWEEN 1 AND 160),
  job_id uuid NOT NULL REFERENCES public.jobs(id) ON DELETE RESTRICT,
  job_number text NOT NULL CHECK (length(btrim(job_number)) > 0),
  attendance_cycle_id uuid
    REFERENCES public.makesafe_attendance_cycles(id) ON DELETE RESTRICT,
  state text NOT NULL CHECK (state IN ('active', 'resolved')),
  code text NOT NULL CHECK (length(btrim(code)) > 0),
  message text NOT NULL CHECK (length(btrim(message)) > 0),
  evidence_refs jsonb NOT NULL DEFAULT '[]'::jsonb
    CHECK (jsonb_typeof(evidence_refs) = 'array'),
  computed_at timestamptz NOT NULL,
  marked_by text NOT NULL CHECK (length(btrim(marked_by)) > 0),
  marked_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT makesafe_board_attention_marks_idempotency
    UNIQUE (run_key, job_id)
);

CREATE INDEX IF NOT EXISTS idx_makesafe_board_attention_marks_current
  ON public.makesafe_board_attention_marks (job_id, marked_at DESC, id DESC);

COMMENT ON TABLE public.makesafe_board_attention_marks IS
  'Append-only display markers for make-safe cards whose status cannot be corrected automatically. Active rows contain the exact plain-English Captain action; resolved rows clear an earlier mark.';

CREATE OR REPLACE FUNCTION public.guard_makesafe_board_attention_mark_insert()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  v_job_number text;
  v_job_type text;
BEGIN
  SELECT job_number, type
  INTO v_job_number, v_job_type
  FROM public.jobs
  WHERE id = NEW.job_id;

  IF NOT FOUND
     OR v_job_type <> 'makesafe'
     OR v_job_number IS DISTINCT FROM NEW.job_number THEN
    RAISE EXCEPTION 'attention mark job identity is not a current make-safe';
  END IF;
  IF NEW.attendance_cycle_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM public.makesafe_attendance_cycles c
    WHERE c.id = NEW.attendance_cycle_id
      AND c.job_id = NEW.job_id
  ) THEN
    RAISE EXCEPTION 'attention mark attendance cycle belongs to another job';
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.reject_makesafe_board_attention_mark_mutation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  RAISE EXCEPTION 'makesafe_board_attention_marks is append-only';
END;
$$;

DROP TRIGGER IF EXISTS trg_makesafe_board_attention_marks_insert_guard
  ON public.makesafe_board_attention_marks;
CREATE TRIGGER trg_makesafe_board_attention_marks_insert_guard
  BEFORE INSERT ON public.makesafe_board_attention_marks
  FOR EACH ROW
  EXECUTE FUNCTION public.guard_makesafe_board_attention_mark_insert();

DROP TRIGGER IF EXISTS trg_makesafe_board_attention_marks_append_only
  ON public.makesafe_board_attention_marks;
CREATE TRIGGER trg_makesafe_board_attention_marks_append_only
  BEFORE UPDATE OR DELETE ON public.makesafe_board_attention_marks
  FOR EACH ROW
  EXECUTE FUNCTION public.reject_makesafe_board_attention_mark_mutation();

CREATE OR REPLACE VIEW public.makesafe_board_attention_current
WITH (security_invoker = true)
AS
SELECT
  id,
  run_key,
  job_id,
  job_number,
  attendance_cycle_id,
  state,
  code,
  message,
  evidence_refs,
  computed_at,
  marked_by,
  marked_at
FROM (
  SELECT DISTINCT ON (job_id) *
  FROM public.makesafe_board_attention_marks
  ORDER BY job_id, marked_at DESC, id DESC
) latest
WHERE state = 'active';

COMMENT ON VIEW public.makesafe_board_attention_current IS
  'Latest unresolved plain-English Captain action for each make-safe card.';

CREATE TABLE IF NOT EXISTS public.makesafe_board_reconciliation_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_key text NOT NULL UNIQUE
    CHECK (length(btrim(run_key)) BETWEEN 1 AND 160),
  selection_hash text NOT NULL
    CHECK (selection_hash ~ '^sha256:[0-9a-f]{64}$'),
  requested_count integer NOT NULL CHECK (requested_count > 0),
  trustworthy_count integer NOT NULL CHECK (trustworthy_count >= 0),
  captain_marked_count integer NOT NULL CHECK (captain_marked_count >= 0),
  neither_count integer NOT NULL CHECK (neither_count = 0),
  transition_count integer NOT NULL CHECK (transition_count >= 0),
  result_json jsonb NOT NULL CHECK (jsonb_typeof(result_json) = 'object'),
  applied_by text NOT NULL CHECK (length(btrim(applied_by)) > 0),
  applied_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT makesafe_board_reconciliation_partition_check CHECK (
    trustworthy_count + captain_marked_count = requested_count
  )
);

COMMENT ON TABLE public.makesafe_board_reconciliation_runs IS
  'Committed full-selection audit for fact-derived display corrections and Captain markers. Chunks are staged separately and become visible only at finalization.';

CREATE TABLE IF NOT EXISTS public.makesafe_board_reconciliation_staged_chunks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_key text NOT NULL,
  selection_hash text NOT NULL
    CHECK (selection_hash ~ '^sha256:[0-9a-f]{64}$'),
  state_token_hash text NOT NULL
    CHECK (state_token_hash ~ '^sha256:[0-9a-f]{64}$'),
  chunk_index integer NOT NULL CHECK (chunk_index > 0),
  chunk_count integer NOT NULL CHECK (chunk_count > 0),
  rows_json jsonb NOT NULL CHECK (jsonb_typeof(rows_json) = 'array'),
  requested_count integer NOT NULL CHECK (requested_count BETWEEN 1 AND 500),
  staged_by text NOT NULL CHECK (length(btrim(staged_by)) > 0),
  staged_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (run_key, chunk_index)
);

COMMENT ON TABLE public.makesafe_board_reconciliation_staged_chunks IS
  'Invisible, idempotent reconciliation chunks. Only finalize_makesafe_board_reconciliation may publish them.';

CREATE OR REPLACE FUNCTION public.stage_makesafe_board_reconciliation(
  p_run_key text,
  p_applied_by text,
  p_selection_hash text,
  p_state_token_hash text,
  p_chunk_index integer,
  p_chunk_count integer,
  p_rows jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_requested integer;
  v_existing public.makesafe_board_reconciliation_staged_chunks%ROWTYPE;
BEGIN
  DELETE FROM public.makesafe_board_reconciliation_staged_chunks
  WHERE staged_at < now() - interval '24 hours';
  IF length(btrim(COALESCE(p_run_key, ''))) = 0
     OR length(btrim(COALESCE(p_applied_by, ''))) = 0
     OR COALESCE(p_selection_hash, '') !~ '^sha256:[0-9a-f]{64}$'
     OR COALESCE(p_state_token_hash, '') !~ '^sha256:[0-9a-f]{64}$'
     OR p_chunk_index < 1 OR p_chunk_count < p_chunk_index THEN
    RAISE EXCEPTION 'invalid reconciliation staging metadata';
  END IF;
  IF jsonb_typeof(p_rows) <> 'array' THEN
    RAISE EXCEPTION 'p_rows must be a JSON array';
  END IF;
  v_requested := jsonb_array_length(p_rows);
  IF v_requested < 1 OR v_requested > 500 THEN
    RAISE EXCEPTION 'p_rows must contain between 1 and 500 cards';
  END IF;
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements(p_rows) row_json
    WHERE jsonb_typeof(row_json->'state_token') <> 'string'
       OR COALESCE(row_json->>'state_token', '') !~ '^sha256:[0-9a-f]{64}$'
  ) THEN
    RAISE EXCEPTION 'every staged row requires a v2 state token';
  END IF;
  SELECT * INTO v_existing
  FROM public.makesafe_board_reconciliation_staged_chunks
  WHERE run_key = p_run_key AND chunk_index = p_chunk_index;
  IF FOUND THEN
    IF v_existing.selection_hash IS DISTINCT FROM p_selection_hash
       OR v_existing.state_token_hash IS DISTINCT FROM p_state_token_hash
       OR v_existing.chunk_count IS DISTINCT FROM p_chunk_count
       OR v_existing.rows_json IS DISTINCT FROM p_rows THEN
      RAISE EXCEPTION 'staged chunk retry does not match the original payload';
    END IF;
    RETURN jsonb_build_object(
      'ok', true, 'run_key', p_run_key, 'chunk_index', p_chunk_index,
      'requested', v_existing.requested_count, 'idempotent_replay', true
    );
  END IF;
  INSERT INTO public.makesafe_board_reconciliation_staged_chunks (
    run_key, selection_hash, state_token_hash, chunk_index, chunk_count,
    rows_json, requested_count, staged_by
  ) VALUES (
    p_run_key, p_selection_hash, p_state_token_hash, p_chunk_index,
    p_chunk_count, p_rows, v_requested, p_applied_by
  );
  RETURN jsonb_build_object(
    'ok', true, 'run_key', p_run_key, 'chunk_index', p_chunk_index,
    'requested', v_requested, 'idempotent_replay', false
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.validate_makesafe_board_reconciliation_state_tokens(
  p_rows jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF jsonb_typeof(p_rows) <> 'array' THEN
    RAISE EXCEPTION 'reconciliation state token payload must be an array';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.finalize_makesafe_board_reconciliation(
  p_run_key text,
  p_applied_by text,
  p_selection_hash text,
  p_state_token_hash text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_chunk_count integer;
  v_staged_count integer;
  v_rows jsonb := '[]'::jsonb;
  v_chunk public.makesafe_board_reconciliation_staged_chunks%ROWTYPE;
  v_job_id uuid;
  v_result jsonb;
BEGIN
  IF COALESCE(p_selection_hash, '') !~ '^sha256:[0-9a-f]{64}$'
     OR COALESCE(p_state_token_hash, '') !~ '^sha256:[0-9a-f]{64}$' THEN
    RAISE EXCEPTION 'selection and state token hashes are required';
  END IF;
  SELECT max(chunk_count), count(*)::integer
    INTO v_chunk_count, v_staged_count
  FROM public.makesafe_board_reconciliation_staged_chunks
  WHERE run_key = p_run_key
    AND selection_hash = p_selection_hash
    AND state_token_hash = p_state_token_hash;
  IF v_chunk_count IS NULL THEN
    RAISE EXCEPTION 'reconciliation has no staged chunks';
  END IF;
  IF v_staged_count <> v_chunk_count
     OR (SELECT count(*) FROM public.makesafe_board_reconciliation_staged_chunks
      WHERE run_key = p_run_key) <> v_chunk_count
     OR EXISTS (
       SELECT 1
       FROM generate_series(1, v_chunk_count) n
       WHERE NOT EXISTS (
         SELECT 1 FROM public.makesafe_board_reconciliation_staged_chunks c
         WHERE c.run_key = p_run_key AND c.chunk_index = n
       )
     ) THEN
    RAISE EXCEPTION 'reconciliation staging is incomplete';
  END IF;
  FOR v_chunk IN
    SELECT * FROM public.makesafe_board_reconciliation_staged_chunks
    WHERE run_key = p_run_key ORDER BY chunk_index
  LOOP
    v_rows := v_rows || v_chunk.rows_json;
  END LOOP;
  FOR v_job_id IN
    SELECT DISTINCT job_id
    FROM jsonb_to_recordset(v_rows) AS x(job_id uuid)
    WHERE job_id IS NOT NULL
    ORDER BY job_id
  LOOP
    PERFORM 1 FROM public.jobs WHERE id = v_job_id FOR UPDATE;
    PERFORM 1 FROM public.makesafe_state_identity_revisions
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
    PERFORM 1 FROM public.makesafe_attendance_cycles
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
    PERFORM 1 FROM public.job_assignments
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
    PERFORM 1 FROM public.job_service_reports
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
    PERFORM 1 FROM public.job_documents
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
    PERFORM 1 FROM public.job_media
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
    PERFORM 1 FROM public.makesafe_portal_capture_revisions
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
    PERFORM 1 FROM public.makesafe_intake_cases
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
    PERFORM 1 FROM public.makesafe_status_holds
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
    PERFORM 1 FROM public.makesafe_job_details
      WHERE job_id = v_job_id FOR SHARE;
    PERFORM 1 FROM public.makesafe_readiness_revisions
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
    PERFORM 1 FROM public.makesafe_readiness_current
      WHERE job_id = v_job_id FOR SHARE;
    PERFORM 1 FROM public.makesafe_readiness_invalidations
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
    PERFORM 1 FROM public.makesafe_cancellation_decisions
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
    PERFORM 1 FROM public.makesafe_terminal_proofs
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
    PERFORM 1 FROM public.makesafe_report_pack_cycles
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
    PERFORM 1 FROM public.makesafe_report_packs
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
    PERFORM 1 FROM public.makesafe_revision_approvals
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
    PERFORM 1 FROM public.makesafe_board_status_applications
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
    PERFORM 1 FROM public.makesafe_board_attention_marks
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
    PERFORM 1
      FROM public.makesafe_family_rule_current c
      JOIN public.makesafe_state_identity_current_v2 i
        ON i.family_rule_key = c.family_code
       AND i.job_id = v_job_id
      JOIN public.makesafe_family_rule_revisions r
        ON r.id = c.revision_id
      FOR SHARE;
    PERFORM 1 FROM public.makesafe_docket_revisions
      WHERE job_id = v_job_id ORDER BY id FOR SHARE;
  END LOOP;
  PERFORM public.validate_makesafe_board_reconciliation_state_tokens(v_rows);
  v_result := public.apply_makesafe_board_reconciliation(
    p_run_key, p_applied_by, p_selection_hash, v_rows
  );
  DELETE FROM public.makesafe_board_reconciliation_staged_chunks
  WHERE run_key = p_run_key;
  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.validate_makesafe_board_reconciliation_state_tokens(
  p_rows jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row record;
  v_token jsonb;
  v_expected text;
BEGIN
  FOR v_row IN
    SELECT * FROM jsonb_to_recordset(p_rows) AS x(
      job_id uuid,
      state_token text,
      state_facts jsonb
    )
  LOOP
    IF v_row.state_facts IS NULL
       OR jsonb_typeof(v_row.state_facts) <> 'object' THEN
      RAISE EXCEPTION 'reconciliation row % has no state facts', v_row.job_id;
    END IF;
    v_expected := 'sha256:' || encode(
      extensions.digest(
        convert_to(public.makesafe_canonical_json_v1(v_row.state_facts), 'UTF8'),
        'sha256'
      ),
      'hex'
    );
    IF v_row.state_token IS DISTINCT FROM v_expected THEN
      RAISE EXCEPTION 'reconciliation row % has a stale state token', v_row.job_id;
    END IF;
    IF (SELECT count(*) FROM public.makesafe_attendance_cycles WHERE job_id = v_row.job_id)
      <> jsonb_array_length(COALESCE(v_row.state_facts->'cycles', '[]'::jsonb))
      OR (SELECT count(*) FROM public.job_assignments WHERE job_id = v_row.job_id)
      <> jsonb_array_length(COALESCE(v_row.state_facts->'assignments', '[]'::jsonb))
      OR (SELECT count(*) FROM public.job_service_reports WHERE job_id = v_row.job_id)
      <> jsonb_array_length(COALESCE(v_row.state_facts->'service_reports', '[]'::jsonb))
      OR (SELECT count(*) FROM public.job_documents WHERE job_id = v_row.job_id)
      <> jsonb_array_length(COALESCE(v_row.state_facts->'documents', '[]'::jsonb))
      OR (SELECT count(*) FROM public.job_media WHERE job_id = v_row.job_id)
      <> jsonb_array_length(COALESCE(v_row.state_facts->'media', '[]'::jsonb))
      OR (SELECT count(*) FROM public.makesafe_portal_capture_revisions WHERE job_id = v_row.job_id)
      <> jsonb_array_length(COALESCE(v_row.state_facts->'portal_captures', '[]'::jsonb))
    THEN
      RAISE EXCEPTION 'reconciliation row % fact coverage changed', v_row.job_id;
    END IF;
    v_token := v_row.state_facts->'identity';
    IF v_token IS NOT NULL AND NOT EXISTS (
      SELECT 1
      FROM public.makesafe_state_identity_current_v2 i
      WHERE i.job_id = v_row.job_id
        AND i.id = (v_token->>'id')::uuid
        AND i.source_version IS NOT DISTINCT FROM (v_token->>'source_version')::bigint
        AND i.source_content_hash IS NOT DISTINCT FROM v_token->>'source_content_hash'
        AND i.lineage_id IS NOT DISTINCT FROM v_token->>'lineage_id'
        AND i.lineage_version IS NOT DISTINCT FROM (v_token->>'lineage_version')::bigint
        AND i.lineage_correction_hash IS NOT DISTINCT FROM v_token->>'lineage_correction_hash'
        AND i.lineage_supersession_hash IS NOT DISTINCT FROM v_token->>'lineage_supersession_hash'
        AND i.revision_hash IS NOT DISTINCT FROM v_token->>'revision_hash'
    ) THEN
      RAISE EXCEPTION 'reconciliation row % identity facts changed', v_row.job_id;
    END IF;
    v_token := v_row.state_facts->'readiness';
    IF v_token IS NOT NULL AND NOT EXISTS (
      SELECT 1
      FROM public.makesafe_readiness_current_v2 r
      WHERE r.job_id = v_row.job_id
        AND r.ready IS NOT DISTINCT FROM (v_token->>'ready')::boolean
        AND r.readiness_revision IS NOT DISTINCT FROM v_token->>'readiness_revision'
        AND r.dependency_generation IS NOT DISTINCT FROM (v_token->>'dependency_generation')::integer
        AND r.attendance_cycle_set_hash IS NOT DISTINCT FROM v_token->>'attendance_cycle_set_hash'
        AND r.invalidated_at IS NOT DISTINCT FROM (v_token->>'invalidated_at')::timestamptz
        AND r.invalidation_reason IS NOT DISTINCT FROM v_token->>'invalidation_reason'
        AND r.dependency_envelope IS NOT DISTINCT FROM v_token->'dependency_envelope'
    ) THEN
      RAISE EXCEPTION 'reconciliation row % readiness facts changed', v_row.job_id;
    END IF;
    IF EXISTS (
      SELECT 1
      FROM jsonb_array_elements(COALESCE(v_row.state_facts->'cycles', '[]'::jsonb)) e
      LEFT JOIN public.makesafe_attendance_cycles f
        ON f.id = (e->>'id')::uuid AND f.job_id = v_row.job_id
      WHERE f.id IS NULL
         OR f.cycle_number IS DISTINCT FROM (e->>'cycle_number')::integer
         OR f.opened_at IS DISTINCT FROM (e->>'opened_at')::timestamptz
         OR f.closed_at IS DISTINCT FROM (e->>'closed_at')::timestamptz
         OR f.makesafe_fact_version IS DISTINCT FROM (e->>'makesafe_fact_version')::bigint
         OR f.makesafe_content_hash IS DISTINCT FROM e->>'makesafe_content_hash'
    ) THEN RAISE EXCEPTION 'reconciliation row % cycle facts changed', v_row.job_id; END IF;
    IF EXISTS (
      SELECT 1
      FROM jsonb_array_elements(COALESCE(v_row.state_facts->'assignments', '[]'::jsonb)) e
      LEFT JOIN public.job_assignments f
        ON f.id = (e->>'id')::uuid AND f.job_id = v_row.job_id
      WHERE f.id IS NULL
         OR f.makesafe_fact_version IS DISTINCT FROM (e->>'makesafe_fact_version')::bigint
         OR f.makesafe_content_hash IS DISTINCT FROM e->>'makesafe_content_hash'
         OR f.attendance_cycle_id IS DISTINCT FROM NULLIF(e->>'attendance_cycle_id', '')::uuid
         OR f.cycle_attribution IS DISTINCT FROM e->>'cycle_attribution'
    ) THEN RAISE EXCEPTION 'reconciliation row % assignment facts changed', v_row.job_id; END IF;
    IF EXISTS (
      SELECT 1
      FROM jsonb_array_elements(COALESCE(v_row.state_facts->'service_reports', '[]'::jsonb)) e
      LEFT JOIN public.job_service_reports f
        ON f.id = (e->>'id')::uuid AND f.job_id = v_row.job_id
      WHERE f.id IS NULL
         OR f.makesafe_fact_version IS DISTINCT FROM (e->>'makesafe_fact_version')::bigint
         OR f.makesafe_content_hash IS DISTINCT FROM e->>'makesafe_content_hash'
         OR f.attendance_cycle_id IS DISTINCT FROM NULLIF(e->>'attendance_cycle_id', '')::uuid
         OR f.cycle_attribution IS DISTINCT FROM e->>'cycle_attribution'
    ) THEN RAISE EXCEPTION 'reconciliation row % report facts changed', v_row.job_id; END IF;
    IF EXISTS (
      SELECT 1
      FROM jsonb_array_elements(COALESCE(v_row.state_facts->'documents', '[]'::jsonb)) e
      LEFT JOIN public.job_documents f
        ON f.id = (e->>'id')::uuid AND f.job_id = v_row.job_id
      WHERE f.id IS NULL
         OR f.makesafe_fact_version IS DISTINCT FROM (e->>'makesafe_fact_version')::bigint
         OR f.makesafe_content_hash IS DISTINCT FROM e->>'makesafe_content_hash'
         OR f.attendance_cycle_id IS DISTINCT FROM NULLIF(e->>'attendance_cycle_id', '')::uuid
         OR f.cycle_attribution IS DISTINCT FROM e->>'cycle_attribution'
    ) THEN RAISE EXCEPTION 'reconciliation row % document facts changed', v_row.job_id; END IF;
    IF EXISTS (
      SELECT 1
      FROM jsonb_array_elements(COALESCE(v_row.state_facts->'media', '[]'::jsonb)) e
      LEFT JOIN public.job_media f
        ON f.id = (e->>'id')::uuid AND f.job_id = v_row.job_id
      WHERE f.id IS NULL
         OR f.makesafe_fact_version IS DISTINCT FROM (e->>'makesafe_fact_version')::bigint
         OR f.makesafe_content_hash IS DISTINCT FROM e->>'makesafe_content_hash'
         OR f.attendance_cycle_id IS DISTINCT FROM NULLIF(e->>'attendance_cycle_id', '')::uuid
         OR f.cycle_attribution IS DISTINCT FROM e->>'cycle_attribution'
    ) THEN RAISE EXCEPTION 'reconciliation row % media facts changed', v_row.job_id; END IF;
    IF EXISTS (
      SELECT 1
      FROM jsonb_array_elements(COALESCE(v_row.state_facts->'portal_captures', '[]'::jsonb)) e
      LEFT JOIN public.makesafe_portal_capture_revisions f
        ON f.id = (e->>'id')::uuid AND f.job_id = v_row.job_id
      WHERE f.id IS NULL
         OR f.makesafe_fact_version IS DISTINCT FROM (e->>'makesafe_fact_version')::bigint
         OR f.makesafe_content_hash IS DISTINCT FROM e->>'makesafe_content_hash'
         OR f.attendance_cycle_id IS DISTINCT FROM NULLIF(e->>'attendance_cycle_id', '')::uuid
    ) THEN RAISE EXCEPTION 'reconciliation row % portal facts changed', v_row.job_id; END IF;
    v_token := v_row.state_facts->'job';
    IF NOT EXISTS (
      SELECT 1 FROM public.jobs j
      WHERE j.id = v_row.job_id
        AND j.type IS NOT DISTINCT FROM v_token->>'type'
        AND j.status IS NOT DISTINCT FROM v_token->>'status'
        AND j.substatus IS NOT DISTINCT FROM v_token->>'substatus'
        AND j.metadata IS NOT DISTINCT FROM v_row.state_facts->'job_family'->'metadata'
    ) THEN
      RAISE EXCEPTION 'reconciliation row % job state changed', v_row.job_id;
    END IF;
    v_token := v_row.state_facts->'job_details';
    IF (SELECT count(*) FROM public.makesafe_job_details WHERE job_id = v_row.job_id)
      <> CASE WHEN v_token IS NULL THEN 0 ELSE 1 END
      OR (v_token IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM public.makesafe_job_details d
        WHERE d.job_id = v_row.job_id
          AND d.substatus IS NOT DISTINCT FROM v_token->>'substatus'
          AND d.cycle_number IS NOT DISTINCT FROM (v_token->>'cycle_number')::integer
          AND d.attendance_cycle_id IS NOT DISTINCT FROM NULLIF(v_token->>'attendance_cycle_id', '')::uuid
          AND d.cycle_attribution IS NOT DISTINCT FROM v_token->>'cycle_attribution'
          AND d.report_type IS NOT DISTINCT FROM v_token->>'report_type'
          AND d.reopen_reason IS NOT DISTINCT FROM v_token->>'reopen_reason'
          AND d.reattend_count IS NOT DISTINCT FROM (v_token->>'reattend_count')::integer
          AND d.last_reattend_at IS NOT DISTINCT FROM (v_token->>'last_reattend_at')::timestamptz
          AND d.last_reattend_reason IS NOT DISTINCT FROM v_token->>'last_reattend_reason'
          AND d.cancel_reason IS NOT DISTINCT FROM v_token->>'cancel_reason'
          AND d.cancel_note IS NOT DISTINCT FROM v_token->>'cancel_note'
          AND d.cancelled_by IS NOT DISTINCT FROM v_token->>'cancelled_by'
          AND d.cancelled_at IS NOT DISTINCT FROM (v_token->>'cancelled_at')::timestamptz
          AND d.report_received_at IS NOT DISTINCT FROM (v_token->>'report_received_at')::timestamptz
          AND d.report_sent_at IS NOT DISTINCT FROM (v_token->>'report_sent_at')::timestamptz
          AND d.invoice_ready_at IS NOT DISTINCT FROM (v_token->>'invoice_ready_at')::timestamptz
          AND d.invoice_notes IS NOT DISTINCT FROM v_token->>'invoice_notes'
          AND d.safety_requirements IS NOT DISTINCT FROM v_token->>'safety_requirements'
          AND d.special_instructions IS NOT DISTINCT FROM v_token->>'special_instructions'
          AND d.external_links IS NOT DISTINCT FROM v_token->'external_links'
          AND d.billing_rules IS NOT DISTINCT FROM v_token->'billing_rules'
          AND d.portal_verified_at IS NOT DISTINCT FROM (v_token->>'portal_verified_at')::timestamptz
          AND d.portal_verified_cycle IS NOT DISTINCT FROM (v_token->>'portal_verified_cycle')::integer
          AND d.portal_verified_signal IS NOT DISTINCT FROM v_token->>'portal_verified_signal'
          AND d.portal_verified_by IS NOT DISTINCT FROM v_token->>'portal_verified_by'
          AND d.updated_at IS NOT DISTINCT FROM (v_token->>'updated_at')::timestamptz
      )) THEN
      RAISE EXCEPTION 'reconciliation row % job details changed', v_row.job_id;
    END IF;
    v_token := v_row.state_facts->'detail_cycle_binding';
    IF v_token->>'attendance_cycle_id' IS NOT NULL
       AND NOT EXISTS (
         SELECT 1
         FROM public.makesafe_attendance_cycles c
         WHERE c.id = (v_token->>'attendance_cycle_id')::uuid
           AND c.job_id = v_row.job_id
       ) THEN
      RAISE EXCEPTION 'reconciliation row % detail cycle binding changed', v_row.job_id;
    END IF;
    v_token := v_row.state_facts->'docket';
    IF (SELECT count(*) FROM public.makesafe_docket_revisions_current WHERE job_id = v_row.job_id)
      <> CASE WHEN v_token IS NULL THEN 0 ELSE 1 END
      OR (v_token IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM public.makesafe_docket_revisions_current d
        WHERE d.job_id = v_row.job_id
          AND d.id IS NOT DISTINCT FROM (v_token->>'id')::uuid
          AND d.source_instruction_id IS NOT DISTINCT FROM v_token->>'source_instruction_id'
          AND d.lineage_id IS NOT DISTINCT FROM v_token->>'lineage_id'
          AND d.attendance_cycle_ids IS NOT DISTINCT FROM (
            SELECT COALESCE(array_agg(value::uuid), '{}'::uuid[])
            FROM jsonb_array_elements_text(COALESCE(v_token->'attendance_cycle_ids', '[]'::jsonb))
          )
          AND d.current_attendance_cycle_id IS NOT DISTINCT FROM (v_token->>'current_attendance_cycle_id')::uuid
          AND d.readiness_revision IS NOT DISTINCT FROM v_token->>'readiness_revision'
          AND d.input_content_hash IS NOT DISTINCT FROM v_token->>'input_content_hash'
          AND d.output_content_hash IS NOT DISTINCT FROM v_token->>'output_content_hash'
          AND d.state IS NOT DISTINCT FROM v_token->>'state'
          AND d.pre_xero_docs_ready IS NOT DISTINCT FROM (v_token->>'pre_xero_docs_ready')::boolean
          AND d.envelope IS NOT DISTINCT FROM v_token->'envelope'
          AND d.review_spec IS NOT DISTINCT FROM v_token->'review_spec'
          AND d.release_payload IS NOT DISTINCT FROM v_token->'release_payload'
          AND d.committed_at IS NOT DISTINCT FROM (v_token->>'committed_at')::timestamptz
      )) THEN
      RAISE EXCEPTION 'reconciliation row % docket facts changed', v_row.job_id;
    END IF;
    v_token := v_row.state_facts->'cases';
    IF (SELECT count(*) FROM public.makesafe_intake_cases WHERE job_id = v_row.job_id)
      <> jsonb_array_length(COALESCE(v_token, '[]'::jsonb))
      OR EXISTS (
        SELECT 1
        FROM jsonb_array_elements(COALESCE(v_token, '[]'::jsonb)) e
        LEFT JOIN public.makesafe_intake_cases f
          ON f.id = (e->>'id')::uuid AND f.job_id = v_row.job_id
        WHERE f.id IS NULL
           OR f.instruction_key IS DISTINCT FROM e->>'instruction_key'
           OR f.lineage_id IS DISTINCT FROM e->>'lineage_id'
           OR f.state IS DISTINCT FROM e->>'state'
           OR f.state_version IS DISTINCT FROM (e->>'state_version')::integer
           OR f.source_version IS DISTINCT FROM (e->>'source_version')::bigint
           OR f.source_content_hash IS DISTINCT FROM e->>'source_content_hash'
           OR f.lineage_version IS DISTINCT FROM (e->>'lineage_version')::bigint
           OR f.lineage_correction_hash IS DISTINCT FROM e->>'lineage_correction_hash'
           OR f.lineage_supersession_hash IS DISTINCT FROM e->>'lineage_supersession_hash'
           OR f.updated_at IS DISTINCT FROM (e->>'updated_at')::timestamptz
      )
    THEN RAISE EXCEPTION 'reconciliation row % intake-case facts changed', v_row.job_id; END IF;
    v_token := v_row.state_facts->'holds';
    IF (SELECT count(*) FROM public.makesafe_status_holds WHERE job_id = v_row.job_id)
      <> jsonb_array_length(COALESCE(v_token, '[]'::jsonb))
      OR EXISTS (
        SELECT 1
        FROM jsonb_array_elements(COALESCE(v_token, '[]'::jsonb)) e
        LEFT JOIN public.makesafe_status_holds f
          ON f.id = (e->>'id')::uuid AND f.job_id = v_row.job_id
        WHERE f.id IS NULL
           OR f.attendance_cycle_id IS DISTINCT FROM NULLIF(e->>'attendance_cycle_id', '')::uuid
           OR f.blocker_code IS DISTINCT FROM e->>'blocker_code'
           OR f.owner_role IS DISTINCT FROM e->>'owner_role'
           OR f.recovery_action IS DISTINCT FROM e->>'recovery_action'
           OR f.recovery_instruction IS DISTINCT FROM e->>'recovery_instruction'
           OR f.evidence_refs IS DISTINCT FROM e->'evidence_refs'
           OR f.created_at IS DISTINCT FROM (e->>'created_at')::timestamptz
           OR f.lifted_at IS DISTINCT FROM (e->>'lifted_at')::timestamptz
           OR f.note IS DISTINCT FROM e->>'note'
      )
    THEN RAISE EXCEPTION 'reconciliation row % hold facts changed', v_row.job_id; END IF;
    v_token := v_row.state_facts->'family_rule';
    IF v_token IS NULL THEN
      IF EXISTS (
        SELECT 1
        FROM public.makesafe_family_rules_current_v2 f
        JOIN public.makesafe_state_identity_current_v2 i
          ON i.job_id = v_row.job_id
         AND i.family_rule_key = f.family_code
      ) THEN
        RAISE EXCEPTION 'reconciliation row % family rule changed', v_row.job_id;
      END IF;
    ELSIF NOT EXISTS (
      SELECT 1
      FROM public.makesafe_family_rules_current_v2 f
      JOIN public.makesafe_state_identity_current_v2 i
        ON i.job_id = v_row.job_id
       AND i.family_rule_key = f.family_code
      WHERE f.family_code IS NOT DISTINCT FROM v_token->>'family_code'
        AND f.family_kind IS NOT DISTINCT FROM v_token->>'family_kind'
        AND f.matrix_revision IS NOT DISTINCT FROM v_token->>'matrix_revision'
        AND f.matrix_content_hash IS NOT DISTINCT FROM v_token->>'matrix_content_hash'
        AND f.completion_photo_floor IS NOT DISTINCT FROM (v_token->>'completion_photo_floor')::integer
        AND f.required_document_types IS NOT DISTINCT FROM (
          SELECT COALESCE(array_agg(value), '{}'::text[])
          FROM jsonb_array_elements_text(COALESCE(v_token->'required_document_types', '[]'::jsonb))
        )
        AND f.required_portal_roles IS NOT DISTINCT FROM (
          SELECT COALESCE(array_agg(value), '{}'::text[])
          FROM jsonb_array_elements_text(COALESCE(v_token->'required_portal_roles', '[]'::jsonb))
        )
    ) THEN
      RAISE EXCEPTION 'reconciliation row % family rule changed', v_row.job_id;
    END IF;
    v_token := v_row.state_facts->'cancellations';
    IF (SELECT count(*) FROM public.makesafe_cancellation_current_v2 WHERE job_id = v_row.job_id)
      <> jsonb_array_length(COALESCE(v_token, '[]'::jsonb))
      OR EXISTS (
        SELECT 1
        FROM jsonb_array_elements(COALESCE(v_token, '[]'::jsonb)) e
        LEFT JOIN public.makesafe_cancellation_current_v2 f
          ON f.id = (e->>'id')::uuid AND f.job_id = v_row.job_id
        WHERE f.id IS NULL
           OR f.attendance_cycle_set_hash IS DISTINCT FROM e->>'attendance_cycle_set_hash'
           OR f.state IS DISTINCT FROM e->>'state'
           OR f.reason_code IS DISTINCT FROM e->>'reason_code'
           OR f.note IS DISTINCT FROM e->>'note'
           OR f.decided_by IS DISTINCT FROM e->>'decided_by'
           OR f.decided_at IS DISTINCT FROM (e->>'decided_at')::timestamptz
      )
    THEN RAISE EXCEPTION 'reconciliation row % cancellation facts changed', v_row.job_id; END IF;
    v_token := v_row.state_facts->'terminal_proofs';
    IF (SELECT count(*) FROM public.makesafe_terminal_proofs_current_v2 WHERE job_id = v_row.job_id)
      <> jsonb_array_length(COALESCE(v_token, '[]'::jsonb))
      OR EXISTS (
        SELECT 1
        FROM jsonb_array_elements(COALESCE(v_token, '[]'::jsonb)) e
        LEFT JOIN public.makesafe_terminal_proofs_current_v2 f
          ON f.id = (e->>'id')::uuid AND f.job_id = v_row.job_id
        WHERE f.id IS NULL
           OR f.kind IS DISTINCT FROM e->>'kind'
           OR f.attendance_cycle_ids IS DISTINCT FROM (
             SELECT COALESCE(array_agg(value::uuid), '{}'::uuid[])
             FROM jsonb_array_elements_text(COALESCE(e->'attendance_cycle_ids', '[]'::jsonb))
           )
           OR f.readiness_revision IS DISTINCT FROM e->>'readiness_revision'
           OR f.release_revision_id IS DISTINCT FROM NULLIF(e->>'release_revision_id', '')::uuid
           OR f.closeout_revision_id IS DISTINCT FROM NULLIF(e->>'closeout_revision_id', '')::uuid
           OR f.proven_at IS DISTINCT FROM (e->>'proven_at')::timestamptz
      )
    THEN RAISE EXCEPTION 'reconciliation row % terminal proof facts changed', v_row.job_id; END IF;
    v_token := v_row.state_facts->'pack_cycles';
    IF (SELECT count(*) FROM public.makesafe_report_pack_cycles WHERE job_id = v_row.job_id)
      <> jsonb_array_length(COALESCE(v_token, '[]'::jsonb))
      OR EXISTS (
        SELECT 1
        FROM jsonb_array_elements(COALESCE(v_token, '[]'::jsonb)) e
        LEFT JOIN public.makesafe_report_pack_cycles f
          ON f.id = (e->>'id')::uuid AND f.job_id = v_row.job_id
        WHERE f.id IS NULL
           OR f.pack_id IS DISTINCT FROM (e->>'pack_id')::uuid
           OR f.attendance_cycle_id IS DISTINCT FROM (e->>'attendance_cycle_id')::uuid
           OR f.cycle_attribution IS DISTINCT FROM e->>'cycle_attribution'
      )
    THEN RAISE EXCEPTION 'reconciliation row % pack-cycle facts changed', v_row.job_id; END IF;
    v_token := v_row.state_facts->'packs';
    IF (SELECT count(*) FROM public.makesafe_report_packs WHERE job_id = v_row.job_id)
      <> jsonb_array_length(COALESCE(v_token, '[]'::jsonb))
      OR EXISTS (
        SELECT 1
        FROM jsonb_array_elements(COALESCE(v_token, '[]'::jsonb)) e
        LEFT JOIN public.makesafe_report_packs f
          ON f.id = (e->>'id')::uuid AND f.job_id = v_row.job_id
        WHERE f.id IS NULL
           OR f.status IS DISTINCT FROM e->>'status'
           OR f.review_state IS DISTINCT FROM e->>'review_state'
           OR f.needs_money_review IS DISTINCT FROM (e->>'needs_money_review')::boolean
           OR f.last_render_hash IS DISTINCT FROM e->>'last_render_hash'
           OR f.makesafe_fact_version IS DISTINCT FROM (e->>'makesafe_fact_version')::bigint
           OR f.makesafe_content_hash IS DISTINCT FROM e->>'makesafe_content_hash'
      )
    THEN RAISE EXCEPTION 'reconciliation row % pack facts changed', v_row.job_id; END IF;
    v_token := v_row.state_facts->'approvals';
    IF (SELECT count(*) FROM public.makesafe_revision_approvals WHERE job_id = v_row.job_id)
      <> jsonb_array_length(COALESCE(v_token, '[]'::jsonb))
      OR EXISTS (
        SELECT 1
        FROM jsonb_array_elements(COALESCE(v_token, '[]'::jsonb)) e
        LEFT JOIN public.makesafe_revision_approvals f
          ON f.id = (e->>'id')::uuid AND f.job_id = v_row.job_id
        WHERE f.id IS NULL
           OR f.action IS DISTINCT FROM e->>'action'
           OR f.decision IS DISTINCT FROM e->>'decision'
           OR f.readiness_revision IS DISTINCT FROM e->>'readiness_revision'
           OR f.dependency_generation IS DISTINCT FROM (e->>'dependency_generation')::integer
           OR f.docket_revision_id IS DISTINCT FROM NULLIF(e->>'docket_revision_id', '')::uuid
           OR f.release_revision_id IS DISTINCT FROM NULLIF(e->>'release_revision_id', '')::uuid
           OR f.decided_at IS DISTINCT FROM (e->>'decided_at')::timestamptz
      )
    THEN RAISE EXCEPTION 'reconciliation row % approval facts changed', v_row.job_id; END IF;
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION public.discard_makesafe_board_reconciliation(
  p_run_key text,
  p_selection_hash text,
  p_reason text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE v_deleted integer;
BEGIN
  DELETE FROM public.makesafe_board_reconciliation_staged_chunks
  WHERE run_key = p_run_key
    AND (p_selection_hash IS NULL OR selection_hash = p_selection_hash);
  GET DIAGNOSTICS v_deleted = ROW_COUNT;
  RETURN jsonb_build_object('ok', true, 'run_key', p_run_key,
    'discarded_chunks', v_deleted, 'reason', left(COALESCE(p_reason, ''), 500));
END;
$$;

DROP TRIGGER IF EXISTS trg_makesafe_board_reconciliation_runs_append_only
  ON public.makesafe_board_reconciliation_runs;
CREATE TRIGGER trg_makesafe_board_reconciliation_runs_append_only
  BEFORE UPDATE OR DELETE ON public.makesafe_board_reconciliation_runs
  FOR EACH ROW
  EXECUTE FUNCTION public.reject_makesafe_board_attention_mark_mutation();

CREATE OR REPLACE FUNCTION public.apply_makesafe_board_reconciliation(
  p_run_key text,
  p_applied_by text,
  p_selection_hash text,
  p_rows jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_requested integer;
  v_distinct integer;
  v_trustworthy integer;
  v_captain_marked integer;
  v_transitions integer;
  v_attention integer;
  v_result jsonb;
  v_existing public.makesafe_board_reconciliation_runs%ROWTYPE;
BEGIN
  IF length(btrim(COALESCE(p_run_key, ''))) = 0
     OR length(btrim(COALESCE(p_applied_by, ''))) = 0
     OR COALESCE(p_selection_hash, '') !~
       '^sha256:[0-9a-f]{64}$' THEN
    RAISE EXCEPTION
      'run key, attribution, and sha256 selection hash are required';
  END IF;
  IF jsonb_typeof(p_rows) <> 'array' THEN
    RAISE EXCEPTION 'p_rows must be a JSON array';
  END IF;

  SELECT * INTO v_existing
  FROM public.makesafe_board_reconciliation_runs
  WHERE run_key = p_run_key;
  IF FOUND THEN
    IF v_existing.selection_hash IS DISTINCT FROM p_selection_hash THEN
      RAISE EXCEPTION 'run key already belongs to a different selection';
    END IF;
    RETURN v_existing.result_json ||
      jsonb_build_object('idempotent_replay', true);
  END IF;

  v_requested := jsonb_array_length(p_rows);
  IF v_requested < 1 THEN
    RAISE EXCEPTION 'p_rows must contain at least one card';
  END IF;

  WITH incoming AS (
    SELECT *
    FROM jsonb_to_recordset(p_rows) AS x(
      job_id uuid,
      job_number text,
      outcome text,
      source_status text,
      before_status text,
      after_status text,
      computed_at timestamptz,
      computed_reasons jsonb,
      attendance_cycle_id uuid,
      attention_state text,
      attention_code text,
      attention_message text,
      attention_since timestamptz,
      attention_evidence_refs jsonb
    )
  )
  SELECT
    count(DISTINCT i.job_id),
    count(*) FILTER (WHERE i.outcome = 'trustworthy'),
    count(*) FILTER (WHERE i.outcome = 'captain_marked'),
    count(*) FILTER (WHERE i.after_status IS NOT NULL),
    count(*) FILTER (WHERE i.attention_state IS NOT NULL)
  INTO
    v_distinct,
    v_trustworthy,
    v_captain_marked,
    v_transitions,
    v_attention
  FROM incoming i
  JOIN public.jobs j
    ON j.id = i.job_id
   AND j.job_number = i.job_number
   AND j.type = 'makesafe'
  WHERE i.outcome IN ('trustworthy', 'captain_marked')
    AND (
      (i.outcome = 'captain_marked' AND i.attention_state = 'active')
      OR i.outcome = 'trustworthy'
    )
    AND (
      i.attention_state IS NULL
      OR (
        i.attention_state IN ('active', 'resolved')
        AND length(btrim(COALESCE(i.attention_code, ''))) > 0
        AND length(btrim(COALESCE(i.attention_message, ''))) > 0
        AND i.attention_since IS NOT NULL
        AND jsonb_typeof(
          COALESCE(i.attention_evidence_refs, '[]'::jsonb)
        ) = 'array'
      )
    );

  IF v_distinct <> v_requested
     OR v_trustworthy + v_captain_marked <> v_requested THEN
    RAISE EXCEPTION
      'reconciliation must partition every current make-safe exactly once';
  END IF;

  -- Verify every proposed display transition against the latest display overlay.
  IF EXISTS (
    WITH incoming AS (
      SELECT *
      FROM jsonb_to_recordset(p_rows) AS x(
        job_id uuid,
        job_number text,
        outcome text,
        source_status text,
        before_status text,
        after_status text,
        computed_at timestamptz,
        computed_reasons jsonb,
        attendance_cycle_id uuid,
        attention_state text,
        attention_code text,
        attention_message text,
        attention_since timestamptz,
        attention_evidence_refs jsonb
      )
    )
    SELECT 1
    FROM incoming i
    JOIN public.jobs j ON j.id = i.job_id
    LEFT JOIN LATERAL (
      SELECT a.after_status
      FROM public.makesafe_board_status_applications a
      WHERE a.job_id = i.job_id
        AND a.source_status = i.source_status
      ORDER BY a.applied_at DESC, a.id DESC
      LIMIT 1
    ) latest ON true
    WHERE i.after_status IS NOT NULL
      AND (
        i.outcome <> 'trustworthy'
        OR lower(COALESCE(j.status, '')) IN (
          'archived', 'complete', 'completed', 'closed',
          'cancelled', 'canceled', 'lost', 'deleted'
        )
        OR i.source_status NOT IN (
          'new', 'allocated', 'trade_report_in', 'report_ready'
        )
        OR i.before_status NOT IN (
          'new', 'allocated', 'trade_report_in', 'report_ready'
        )
        OR i.after_status NOT IN (
          'new', 'allocated', 'trade_report_in', 'report_ready',
          'completed', 'archive', 'cancelled'
        )
        OR i.before_status = i.after_status
        OR i.computed_at IS NULL
        OR jsonb_typeof(COALESCE(i.computed_reasons, '[]'::jsonb))
          <> 'array'
        OR jsonb_array_length(
          COALESCE(i.computed_reasons, '[]'::jsonb)
        ) = 0
        OR COALESCE(latest.after_status, i.source_status)
          IS DISTINCT FROM i.before_status
      )
  ) THEN
    RAISE EXCEPTION
      'one or more status corrections are stale, terminal, or lack evidence';
  END IF;

  WITH incoming AS (
    SELECT *
    FROM jsonb_to_recordset(p_rows) AS x(
      job_id uuid,
      job_number text,
      outcome text,
      source_status text,
      before_status text,
      after_status text,
      computed_at timestamptz,
      computed_reasons jsonb,
      attendance_cycle_id uuid,
      attention_state text,
      attention_code text,
      attention_message text,
      attention_since timestamptz,
      attention_evidence_refs jsonb
    )
  )
  INSERT INTO public.makesafe_board_status_applications (
    run_key,
    job_id,
    job_number,
    source_status,
    before_status,
    after_status,
    computed_at,
    computed_reasons,
    computed_missing,
    evidence_ref,
    applied_by
  )
  SELECT
    p_run_key,
    i.job_id,
    i.job_number,
    i.source_status,
    i.before_status,
    i.after_status,
    i.computed_at,
    i.computed_reasons,
    '[]'::jsonb,
    'makesafe-state.v2:' || p_selection_hash,
    p_applied_by
  FROM incoming i
  WHERE i.after_status IS NOT NULL;

  WITH incoming AS (
    SELECT *
    FROM jsonb_to_recordset(p_rows) AS x(
      job_id uuid,
      job_number text,
      outcome text,
      source_status text,
      before_status text,
      after_status text,
      computed_at timestamptz,
      computed_reasons jsonb,
      attendance_cycle_id uuid,
      attention_state text,
      attention_code text,
      attention_message text,
      attention_since timestamptz,
      attention_evidence_refs jsonb
    )
  )
  INSERT INTO public.makesafe_board_attention_marks (
    run_key,
    job_id,
    job_number,
    attendance_cycle_id,
    state,
    code,
    message,
    evidence_refs,
    computed_at,
    marked_by
  )
  SELECT
    p_run_key,
    i.job_id,
    i.job_number,
    i.attendance_cycle_id,
    i.attention_state,
    i.attention_code,
    i.attention_message,
    COALESCE(i.attention_evidence_refs, '[]'::jsonb),
    i.attention_since,
    p_applied_by
  FROM incoming i
  WHERE i.attention_state IS NOT NULL;

  v_result := jsonb_build_object(
    'ok', true,
    'run_key', p_run_key,
    'selection_hash', p_selection_hash,
    'requested', v_requested,
    'trustworthy', v_trustworthy,
    'captain_marked', v_captain_marked,
    'neither', 0,
    'transition_count', v_transitions,
    'attention_write_count', v_attention,
    'idempotent_replay', false
  );

  INSERT INTO public.makesafe_board_reconciliation_runs (
    run_key,
    selection_hash,
    requested_count,
    trustworthy_count,
    captain_marked_count,
    neither_count,
    transition_count,
    result_json,
    applied_by
  ) VALUES (
    p_run_key,
    p_selection_hash,
    v_requested,
    v_trustworthy,
    v_captain_marked,
    0,
    v_transitions,
    v_result,
    p_applied_by
  );

  RETURN v_result;
END;
$$;

ALTER TABLE public.makesafe_state_identity_revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.makesafe_state_seed_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.makesafe_board_attention_marks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.makesafe_board_reconciliation_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.makesafe_board_reconciliation_staged_chunks ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.makesafe_state_identity_revisions
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.makesafe_state_identity_current_v2
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.makesafe_state_seed_runs
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.makesafe_board_attention_marks
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.makesafe_board_attention_current
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.makesafe_board_reconciliation_runs
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.makesafe_board_reconciliation_staged_chunks
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.apply_makesafe_board_reconciliation(
  text, text, text, jsonb
) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.stage_makesafe_board_reconciliation(
  text, text, text, text, integer, integer, jsonb
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.finalize_makesafe_board_reconciliation(
  text, text, text, text
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.validate_makesafe_board_reconciliation_state_tokens(
  jsonb
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.discard_makesafe_board_reconciliation(
  text, text, text
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.seed_makesafe_state_authority_v1(
  text, text, text, uuid[]
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.makesafe_fact_hash_v1(text, jsonb)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.stamp_makesafe_fact_identity_v1()
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.stamp_makesafe_intake_case_identity_v1()
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.refresh_makesafe_case_lineage_identity_v1()
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.reject_makesafe_state_seed_audit_mutation()
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.guard_makesafe_board_attention_mark_insert()
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.reject_makesafe_board_attention_mark_mutation()
  FROM PUBLIC, anon, authenticated;

GRANT SELECT, INSERT ON public.makesafe_state_identity_revisions
  TO service_role;
GRANT SELECT ON public.makesafe_state_identity_current_v2 TO service_role;
GRANT SELECT, INSERT ON public.makesafe_state_seed_runs TO service_role;
GRANT SELECT, INSERT ON public.makesafe_board_attention_marks TO service_role;
GRANT SELECT ON public.makesafe_board_attention_current TO service_role;
GRANT SELECT, INSERT ON public.makesafe_board_reconciliation_runs
  TO service_role;
GRANT SELECT, INSERT ON public.makesafe_board_reconciliation_staged_chunks
  TO service_role;
GRANT USAGE, SELECT ON SEQUENCE
  public.makesafe_board_reconciliation_staged_chunks_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE
  public.makesafe_state_seed_runs_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE
  public.makesafe_board_attention_marks_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE
  public.makesafe_board_reconciliation_runs_id_seq TO service_role;
GRANT EXECUTE ON FUNCTION public.stage_makesafe_board_reconciliation(
  text, text, text, text, integer, integer, jsonb
) TO service_role;
GRANT EXECUTE ON FUNCTION public.finalize_makesafe_board_reconciliation(
  text, text, text, text
) TO service_role;
GRANT EXECUTE ON FUNCTION public.discard_makesafe_board_reconciliation(
  text, text, text
) TO service_role;
GRANT EXECUTE ON FUNCTION public.seed_makesafe_state_authority_v1(
  text, text, text, uuid[]
) TO service_role;
GRANT EXECUTE ON FUNCTION public.makesafe_fact_hash_v1(text, jsonb)
  TO service_role;

DROP POLICY IF EXISTS service_role_read_makesafe_state_identity_revisions
  ON public.makesafe_state_identity_revisions;
CREATE POLICY service_role_read_makesafe_state_identity_revisions
  ON public.makesafe_state_identity_revisions
  FOR SELECT TO service_role USING (true);
DROP POLICY IF EXISTS service_role_insert_makesafe_state_identity_revisions
  ON public.makesafe_state_identity_revisions;
CREATE POLICY service_role_insert_makesafe_state_identity_revisions
  ON public.makesafe_state_identity_revisions
  FOR INSERT TO service_role WITH CHECK (true);
DROP POLICY IF EXISTS service_role_read_makesafe_state_seed_runs
  ON public.makesafe_state_seed_runs;
CREATE POLICY service_role_read_makesafe_state_seed_runs
  ON public.makesafe_state_seed_runs
  FOR SELECT TO service_role USING (true);
DROP POLICY IF EXISTS service_role_insert_makesafe_state_seed_runs
  ON public.makesafe_state_seed_runs;
CREATE POLICY service_role_insert_makesafe_state_seed_runs
  ON public.makesafe_state_seed_runs
  FOR INSERT TO service_role WITH CHECK (true);
DROP POLICY IF EXISTS service_role_read_makesafe_board_attention_marks
  ON public.makesafe_board_attention_marks;
CREATE POLICY service_role_read_makesafe_board_attention_marks
  ON public.makesafe_board_attention_marks
  FOR SELECT TO service_role USING (true);
DROP POLICY IF EXISTS service_role_insert_makesafe_board_attention_marks
  ON public.makesafe_board_attention_marks;
CREATE POLICY service_role_insert_makesafe_board_attention_marks
  ON public.makesafe_board_attention_marks
  FOR INSERT TO service_role WITH CHECK (true);
DROP POLICY IF EXISTS service_role_read_makesafe_board_reconciliation_runs
  ON public.makesafe_board_reconciliation_runs;
CREATE POLICY service_role_read_makesafe_board_reconciliation_runs
  ON public.makesafe_board_reconciliation_runs
  FOR SELECT TO service_role USING (true);
DROP POLICY IF EXISTS service_role_insert_makesafe_board_reconciliation_runs
  ON public.makesafe_board_reconciliation_runs;
CREATE POLICY service_role_insert_makesafe_board_reconciliation_runs
  ON public.makesafe_board_reconciliation_runs
  FOR INSERT TO service_role WITH CHECK (true);
